// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::collider_type_type::ColliderType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Collider {
    pub id: u64,
    pub world_id: u64,
    pub collider_type: ColliderType,
    pub radius: f32,
    pub half_height: f32,
    pub half_extent_x: f32,
    pub half_extent_y: f32,
    pub half_extent_z: f32,
    pub vertex_a_x: f32,
    pub vertex_a_y: f32,
    pub vertex_a_z: f32,
    pub vertex_b_x: f32,
    pub vertex_b_y: f32,
    pub vertex_b_z: f32,
    pub vertex_c_x: f32,
    pub vertex_c_y: f32,
    pub vertex_c_z: f32,
    pub is_sensor: bool,
    pub collision_memberships: u32,
    pub collision_filter: u32,
    pub normal_x: f32,
    pub normal_y: f32,
    pub normal_z: f32,
}

impl __sdk::InModule for Collider {
    type Module = super::RemoteModule;
}
