// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::game_mode_type::GameMode;
use super::map_id_type::MapId;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateLobbyArgs {
    pub name: String,
    pub map_id: MapId,
    pub game_mode: GameMode,
    pub max_players: u8,
    pub score_limit: i32,
    pub password: String,
    pub custom_map_json: String,
}

impl From<CreateLobbyArgs> for super::Reducer {
    fn from(args: CreateLobbyArgs) -> Self {
        Self::CreateLobby {
            name: args.name,
            map_id: args.map_id,
            game_mode: args.game_mode,
            max_players: args.max_players,
            score_limit: args.score_limit,
            password: args.password,
            custom_map_json: args.custom_map_json,
        }
    }
}

impl __sdk::InModule for CreateLobbyArgs {
    type Module = super::RemoteModule;
}

pub struct CreateLobbyCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_lobby`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_lobby {
    /// Request that the remote module invoke the reducer `create_lobby` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_lobby`] callbacks.
    fn create_lobby(
        &self,
        name: String,
        map_id: MapId,
        game_mode: GameMode,
        max_players: u8,
        score_limit: i32,
        password: String,
        custom_map_json: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_lobby`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateLobbyCallbackId`] can be passed to [`Self::remove_on_create_lobby`]
    /// to cancel the callback.
    fn on_create_lobby(
        &self,
        callback: impl FnMut(
                &super::ReducerEventContext,
                &String,
                &MapId,
                &GameMode,
                &u8,
                &i32,
                &String,
                &String,
            ) + Send
            + 'static,
    ) -> CreateLobbyCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_lobby`],
    /// causing it not to run in the future.
    fn remove_on_create_lobby(&self, callback: CreateLobbyCallbackId);
}

impl create_lobby for super::RemoteReducers {
    fn create_lobby(
        &self,
        name: String,
        map_id: MapId,
        game_mode: GameMode,
        max_players: u8,
        score_limit: i32,
        password: String,
        custom_map_json: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "create_lobby",
            CreateLobbyArgs {
                name,
                map_id,
                game_mode,
                max_players,
                score_limit,
                password,
                custom_map_json,
            },
        )
    }
    fn on_create_lobby(
        &self,
        mut callback: impl FnMut(
                &super::ReducerEventContext,
                &String,
                &MapId,
                &GameMode,
                &u8,
                &i32,
                &String,
                &String,
            ) + Send
            + 'static,
    ) -> CreateLobbyCallbackId {
        CreateLobbyCallbackId(self.imp.on_reducer(
            "create_lobby",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::CreateLobby {
                                    name,
                                    map_id,
                                    game_mode,
                                    max_players,
                                    score_limit,
                                    password,
                                    custom_map_json,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(
                    ctx,
                    name,
                    map_id,
                    game_mode,
                    max_players,
                    score_limit,
                    password,
                    custom_map_json,
                )
            }),
        ))
    }
    fn remove_on_create_lobby(&self, callback: CreateLobbyCallbackId) {
        self.imp.remove_on_reducer("create_lobby", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_lobby`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_lobby {
    /// Set the call-reducer flags for the reducer `create_lobby` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_lobby(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_lobby for super::SetReducerFlags {
    fn create_lobby(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_lobby", flags);
    }
}
