// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::damage_zone_type::DamageZone;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `damage_zone`.
///
/// Obtain a handle from the [`DamageZoneTableAccess::damage_zone`] method on [`super::RemoteTables`],
/// like `ctx.db.damage_zone()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.damage_zone().on_insert(...)`.
pub struct DamageZoneTableHandle<'ctx> {
    imp: __sdk::TableHandle<DamageZone>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `damage_zone`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DamageZoneTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DamageZoneTableHandle`], which mediates access to the table `damage_zone`.
    fn damage_zone(&self) -> DamageZoneTableHandle<'_>;
}

impl DamageZoneTableAccess for super::RemoteTables {
    fn damage_zone(&self) -> DamageZoneTableHandle<'_> {
        DamageZoneTableHandle {
            imp: self.imp.get_table::<DamageZone>("damage_zone"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DamageZoneInsertCallbackId(__sdk::CallbackId);
pub struct DamageZoneDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DamageZoneTableHandle<'ctx> {
    type Row = DamageZone;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DamageZone> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DamageZoneInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DamageZoneInsertCallbackId {
        DamageZoneInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DamageZoneInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DamageZoneDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DamageZoneDeleteCallbackId {
        DamageZoneDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DamageZoneDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DamageZone>("damage_zone");
    _table.add_unique_constraint::<u64>("trigger_id", |row| &row.trigger_id);
}
pub struct DamageZoneUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DamageZoneTableHandle<'ctx> {
    type UpdateCallbackId = DamageZoneUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DamageZoneUpdateCallbackId {
        DamageZoneUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DamageZoneUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<DamageZone>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DamageZone>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `trigger_id` unique index on the table `damage_zone`,
/// which allows point queries on the field of the same name
/// via the [`DamageZoneTriggerIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.damage_zone().trigger_id().find(...)`.
pub struct DamageZoneTriggerIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DamageZone, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DamageZoneTableHandle<'ctx> {
    /// Get a handle on the `trigger_id` unique index on the table `damage_zone`.
    pub fn trigger_id(&self) -> DamageZoneTriggerIdUnique<'ctx> {
        DamageZoneTriggerIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("trigger_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DamageZoneTriggerIdUnique<'ctx> {
    /// Find the subscribed row whose `trigger_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<DamageZone> {
        self.imp.find(col_val)
    }
}
