// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugPlayerInWallArgs {
    pub player_identity: __sdk::Identity,
}

impl From<DebugPlayerInWallArgs> for super::Reducer {
    fn from(args: DebugPlayerInWallArgs) -> Self {
        Self::DebugPlayerInWall {
            player_identity: args.player_identity,
        }
    }
}

impl __sdk::InModule for DebugPlayerInWallArgs {
    type Module = super::RemoteModule;
}

pub struct DebugPlayerInWallCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_player_in_wall`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_player_in_wall {
    /// Request that the remote module invoke the reducer `debug_player_in_wall` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_debug_player_in_wall`] callbacks.
    fn debug_player_in_wall(&self, player_identity: __sdk::Identity) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `debug_player_in_wall`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DebugPlayerInWallCallbackId`] can be passed to [`Self::remove_on_debug_player_in_wall`]
    /// to cancel the callback.
    fn on_debug_player_in_wall(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity) + Send + 'static,
    ) -> DebugPlayerInWallCallbackId;
    /// Cancel a callback previously registered by [`Self::on_debug_player_in_wall`],
    /// causing it not to run in the future.
    fn remove_on_debug_player_in_wall(&self, callback: DebugPlayerInWallCallbackId);
}

impl debug_player_in_wall for super::RemoteReducers {
    fn debug_player_in_wall(&self, player_identity: __sdk::Identity) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "debug_player_in_wall",
            DebugPlayerInWallArgs { player_identity },
        )
    }
    fn on_debug_player_in_wall(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity) + Send + 'static,
    ) -> DebugPlayerInWallCallbackId {
        DebugPlayerInWallCallbackId(self.imp.on_reducer(
            "debug_player_in_wall",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DebugPlayerInWall { player_identity },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, player_identity)
            }),
        ))
    }
    fn remove_on_debug_player_in_wall(&self, callback: DebugPlayerInWallCallbackId) {
        self.imp
            .remove_on_reducer("debug_player_in_wall", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `debug_player_in_wall`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_debug_player_in_wall {
    /// Set the call-reducer flags for the reducer `debug_player_in_wall` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn debug_player_in_wall(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_debug_player_in_wall for super::SetReducerFlags {
    fn debug_player_in_wall(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("debug_player_in_wall", flags);
    }
}
