// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::debug_photon_beam_target_type::DebugPhotonBeamTarget;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `debug_photon_beam_target`.
///
/// Obtain a handle from the [`DebugPhotonBeamTargetTableAccess::debug_photon_beam_target`] method on [`super::RemoteTables`],
/// like `ctx.db.debug_photon_beam_target()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.debug_photon_beam_target().on_insert(...)`.
pub struct DebugPhotonBeamTargetTableHandle<'ctx> {
    imp: __sdk::TableHandle<DebugPhotonBeamTarget>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `debug_photon_beam_target`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DebugPhotonBeamTargetTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DebugPhotonBeamTargetTableHandle`], which mediates access to the table `debug_photon_beam_target`.
    fn debug_photon_beam_target(&self) -> DebugPhotonBeamTargetTableHandle<'_>;
}

impl DebugPhotonBeamTargetTableAccess for super::RemoteTables {
    fn debug_photon_beam_target(&self) -> DebugPhotonBeamTargetTableHandle<'_> {
        DebugPhotonBeamTargetTableHandle {
            imp: self
                .imp
                .get_table::<DebugPhotonBeamTarget>("debug_photon_beam_target"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DebugPhotonBeamTargetInsertCallbackId(__sdk::CallbackId);
pub struct DebugPhotonBeamTargetDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DebugPhotonBeamTargetTableHandle<'ctx> {
    type Row = DebugPhotonBeamTarget;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DebugPhotonBeamTarget> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DebugPhotonBeamTargetInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DebugPhotonBeamTargetInsertCallbackId {
        DebugPhotonBeamTargetInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DebugPhotonBeamTargetInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DebugPhotonBeamTargetDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DebugPhotonBeamTargetDeleteCallbackId {
        DebugPhotonBeamTargetDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DebugPhotonBeamTargetDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<DebugPhotonBeamTarget>("debug_photon_beam_target");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}
pub struct DebugPhotonBeamTargetUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DebugPhotonBeamTargetTableHandle<'ctx> {
    type UpdateCallbackId = DebugPhotonBeamTargetUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DebugPhotonBeamTargetUpdateCallbackId {
        DebugPhotonBeamTargetUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DebugPhotonBeamTargetUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<DebugPhotonBeamTarget>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DebugPhotonBeamTarget>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `identity` unique index on the table `debug_photon_beam_target`,
/// which allows point queries on the field of the same name
/// via the [`DebugPhotonBeamTargetIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.debug_photon_beam_target().identity().find(...)`.
pub struct DebugPhotonBeamTargetIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DebugPhotonBeamTarget, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DebugPhotonBeamTargetTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `debug_photon_beam_target`.
    pub fn identity(&self) -> DebugPhotonBeamTargetIdentityUnique<'ctx> {
        DebugPhotonBeamTargetIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DebugPhotonBeamTargetIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<DebugPhotonBeamTarget> {
        self.imp.find(col_val)
    }
}
