// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugCollisionBodiesArgs {
    pub world_id: u64,
}

impl From<DebugCollisionBodiesArgs> for super::Reducer {
    fn from(args: DebugCollisionBodiesArgs) -> Self {
        Self::DebugCollisionBodies {
            world_id: args.world_id,
        }
    }
}

impl __sdk::InModule for DebugCollisionBodiesArgs {
    type Module = super::RemoteModule;
}

pub struct DebugCollisionBodiesCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_collision_bodies`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_collision_bodies {
    /// Request that the remote module invoke the reducer `debug_collision_bodies` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_debug_collision_bodies`] callbacks.
    fn debug_collision_bodies(&self, world_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `debug_collision_bodies`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DebugCollisionBodiesCallbackId`] can be passed to [`Self::remove_on_debug_collision_bodies`]
    /// to cancel the callback.
    fn on_debug_collision_bodies(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> DebugCollisionBodiesCallbackId;
    /// Cancel a callback previously registered by [`Self::on_debug_collision_bodies`],
    /// causing it not to run in the future.
    fn remove_on_debug_collision_bodies(&self, callback: DebugCollisionBodiesCallbackId);
}

impl debug_collision_bodies for super::RemoteReducers {
    fn debug_collision_bodies(&self, world_id: u64) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "debug_collision_bodies",
            DebugCollisionBodiesArgs { world_id },
        )
    }
    fn on_debug_collision_bodies(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> DebugCollisionBodiesCallbackId {
        DebugCollisionBodiesCallbackId(self.imp.on_reducer(
            "debug_collision_bodies",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DebugCollisionBodies { world_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, world_id)
            }),
        ))
    }
    fn remove_on_debug_collision_bodies(&self, callback: DebugCollisionBodiesCallbackId) {
        self.imp
            .remove_on_reducer("debug_collision_bodies", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `debug_collision_bodies`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_debug_collision_bodies {
    /// Set the call-reducer flags for the reducer `debug_collision_bodies` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn debug_collision_bodies(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_debug_collision_bodies for super::SetReducerFlags {
    fn debug_collision_bodies(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("debug_collision_bodies", flags);
    }
}
