// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugPhysicsWorldArgs {
    pub world_id: u64,
}

impl From<DebugPhysicsWorldArgs> for super::Reducer {
    fn from(args: DebugPhysicsWorldArgs) -> Self {
        Self::DebugPhysicsWorld {
            world_id: args.world_id,
        }
    }
}

impl __sdk::InModule for DebugPhysicsWorldArgs {
    type Module = super::RemoteModule;
}

pub struct DebugPhysicsWorldCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_physics_world`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_physics_world {
    /// Request that the remote module invoke the reducer `debug_physics_world` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_debug_physics_world`] callbacks.
    fn debug_physics_world(&self, world_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `debug_physics_world`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DebugPhysicsWorldCallbackId`] can be passed to [`Self::remove_on_debug_physics_world`]
    /// to cancel the callback.
    fn on_debug_physics_world(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> DebugPhysicsWorldCallbackId;
    /// Cancel a callback previously registered by [`Self::on_debug_physics_world`],
    /// causing it not to run in the future.
    fn remove_on_debug_physics_world(&self, callback: DebugPhysicsWorldCallbackId);
}

impl debug_physics_world for super::RemoteReducers {
    fn debug_physics_world(&self, world_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("debug_physics_world", DebugPhysicsWorldArgs { world_id })
    }
    fn on_debug_physics_world(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> DebugPhysicsWorldCallbackId {
        DebugPhysicsWorldCallbackId(self.imp.on_reducer(
            "debug_physics_world",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DebugPhysicsWorld { world_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, world_id)
            }),
        ))
    }
    fn remove_on_debug_physics_world(&self, callback: DebugPhysicsWorldCallbackId) {
        self.imp
            .remove_on_reducer("debug_physics_world", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `debug_physics_world`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_debug_physics_world {
    /// Set the call-reducer flags for the reducer `debug_physics_world` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn debug_physics_world(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_debug_physics_world for super::SetReducerFlags {
    fn debug_physics_world(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("debug_physics_world", flags);
    }
}
