// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DetonateRocketArgs {}

impl From<DetonateRocketArgs> for super::Reducer {
    fn from(args: DetonateRocketArgs) -> Self {
        Self::DetonateRocket
    }
}

impl __sdk::InModule for DetonateRocketArgs {
    type Module = super::RemoteModule;
}

pub struct DetonateRocketCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `detonate_rocket`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait detonate_rocket {
    /// Request that the remote module invoke the reducer `detonate_rocket` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_detonate_rocket`] callbacks.
    fn detonate_rocket(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `detonate_rocket`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DetonateRocketCallbackId`] can be passed to [`Self::remove_on_detonate_rocket`]
    /// to cancel the callback.
    fn on_detonate_rocket(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> DetonateRocketCallbackId;
    /// Cancel a callback previously registered by [`Self::on_detonate_rocket`],
    /// causing it not to run in the future.
    fn remove_on_detonate_rocket(&self, callback: DetonateRocketCallbackId);
}

impl detonate_rocket for super::RemoteReducers {
    fn detonate_rocket(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("detonate_rocket", DetonateRocketArgs {})
    }
    fn on_detonate_rocket(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> DetonateRocketCallbackId {
        DetonateRocketCallbackId(self.imp.on_reducer(
            "detonate_rocket",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DetonateRocket {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_detonate_rocket(&self, callback: DetonateRocketCallbackId) {
        self.imp.remove_on_reducer("detonate_rocket", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `detonate_rocket`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_detonate_rocket {
    /// Set the call-reducer flags for the reducer `detonate_rocket` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn detonate_rocket(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_detonate_rocket for super::SetReducerFlags {
    fn detonate_rocket(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("detonate_rocket", flags);
    }
}
