// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EndGameArgs {
    pub lobby_id: u64,
}

impl From<EndGameArgs> for super::Reducer {
    fn from(args: EndGameArgs) -> Self {
        Self::EndGame {
            lobby_id: args.lobby_id,
        }
    }
}

impl __sdk::InModule for EndGameArgs {
    type Module = super::RemoteModule;
}

pub struct EndGameCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `end_game`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait end_game {
    /// Request that the remote module invoke the reducer `end_game` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_end_game`] callbacks.
    fn end_game(&self, lobby_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `end_game`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`EndGameCallbackId`] can be passed to [`Self::remove_on_end_game`]
    /// to cancel the callback.
    fn on_end_game(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> EndGameCallbackId;
    /// Cancel a callback previously registered by [`Self::on_end_game`],
    /// causing it not to run in the future.
    fn remove_on_end_game(&self, callback: EndGameCallbackId);
}

impl end_game for super::RemoteReducers {
    fn end_game(&self, lobby_id: u64) -> __sdk::Result<()> {
        self.imp.call_reducer("end_game", EndGameArgs { lobby_id })
    }
    fn on_end_game(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> EndGameCallbackId {
        EndGameCallbackId(self.imp.on_reducer(
            "end_game",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::EndGame { lobby_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, lobby_id)
            }),
        ))
    }
    fn remove_on_end_game(&self, callback: EndGameCallbackId) {
        self.imp.remove_on_reducer("end_game", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `end_game`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_end_game {
    /// Set the call-reducer flags for the reducer `end_game` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn end_game(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_end_game for super::SetReducerFlags {
    fn end_game(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("end_game", flags);
    }
}
