// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::grenade_type::Grenade;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `grenade`.
///
/// Obtain a handle from the [`GrenadeTableAccess::grenade`] method on [`super::RemoteTables`],
/// like `ctx.db.grenade()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.grenade().on_insert(...)`.
pub struct GrenadeTableHandle<'ctx> {
    imp: __sdk::TableHandle<Grenade>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `grenade`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GrenadeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GrenadeTableHandle`], which mediates access to the table `grenade`.
    fn grenade(&self) -> GrenadeTableHandle<'_>;
}

impl GrenadeTableAccess for super::RemoteTables {
    fn grenade(&self) -> GrenadeTableHandle<'_> {
        GrenadeTableHandle {
            imp: self.imp.get_table::<Grenade>("grenade"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GrenadeInsertCallbackId(__sdk::CallbackId);
pub struct GrenadeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GrenadeTableHandle<'ctx> {
    type Row = Grenade;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Grenade> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GrenadeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GrenadeInsertCallbackId {
        GrenadeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GrenadeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GrenadeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GrenadeDeleteCallbackId {
        GrenadeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GrenadeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Grenade>("grenade");
    _table.add_unique_constraint::<u64>("rigid_body_id", |row| &row.rigid_body_id);
}
pub struct GrenadeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GrenadeTableHandle<'ctx> {
    type UpdateCallbackId = GrenadeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GrenadeUpdateCallbackId {
        GrenadeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GrenadeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Grenade>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Grenade>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `rigid_body_id` unique index on the table `grenade`,
/// which allows point queries on the field of the same name
/// via the [`GrenadeRigidBodyIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.grenade().rigid_body_id().find(...)`.
pub struct GrenadeRigidBodyIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Grenade, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GrenadeTableHandle<'ctx> {
    /// Get a handle on the `rigid_body_id` unique index on the table `grenade`.
    pub fn rigid_body_id(&self) -> GrenadeRigidBodyIdUnique<'ctx> {
        GrenadeRigidBodyIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("rigid_body_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GrenadeRigidBodyIdUnique<'ctx> {
    /// Find the subscribed row whose `rigid_body_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Grenade> {
        self.imp.find(col_val)
    }
}
