// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct JoinLobbyArgs {
    pub lobby_id: u64,
    pub player_name: String,
    pub password: String,
}

impl From<JoinLobbyArgs> for super::Reducer {
    fn from(args: JoinLobbyArgs) -> Self {
        Self::JoinLobby {
            lobby_id: args.lobby_id,
            player_name: args.player_name,
            password: args.password,
        }
    }
}

impl __sdk::InModule for JoinLobbyArgs {
    type Module = super::RemoteModule;
}

pub struct JoinLobbyCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `join_lobby`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait join_lobby {
    /// Request that the remote module invoke the reducer `join_lobby` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_join_lobby`] callbacks.
    fn join_lobby(&self, lobby_id: u64, player_name: String, password: String)
        -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `join_lobby`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`JoinLobbyCallbackId`] can be passed to [`Self::remove_on_join_lobby`]
    /// to cancel the callback.
    fn on_join_lobby(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &String, &String) + Send + 'static,
    ) -> JoinLobbyCallbackId;
    /// Cancel a callback previously registered by [`Self::on_join_lobby`],
    /// causing it not to run in the future.
    fn remove_on_join_lobby(&self, callback: JoinLobbyCallbackId);
}

impl join_lobby for super::RemoteReducers {
    fn join_lobby(
        &self,
        lobby_id: u64,
        player_name: String,
        password: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "join_lobby",
            JoinLobbyArgs {
                lobby_id,
                player_name,
                password,
            },
        )
    }
    fn on_join_lobby(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &String, &String) + Send + 'static,
    ) -> JoinLobbyCallbackId {
        JoinLobbyCallbackId(self.imp.on_reducer(
            "join_lobby",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::JoinLobby {
                                    lobby_id,
                                    player_name,
                                    password,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, lobby_id, player_name, password)
            }),
        ))
    }
    fn remove_on_join_lobby(&self, callback: JoinLobbyCallbackId) {
        self.imp.remove_on_reducer("join_lobby", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `join_lobby`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_join_lobby {
    /// Set the call-reducer flags for the reducer `join_lobby` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn join_lobby(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_join_lobby for super::SetReducerFlags {
    fn join_lobby(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("join_lobby", flags);
    }
}
