// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::lobby_player_type::LobbyPlayer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `lobby_player`.
///
/// Obtain a handle from the [`LobbyPlayerTableAccess::lobby_player`] method on [`super::RemoteTables`],
/// like `ctx.db.lobby_player()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.lobby_player().on_insert(...)`.
pub struct LobbyPlayerTableHandle<'ctx> {
    imp: __sdk::TableHandle<LobbyPlayer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `lobby_player`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LobbyPlayerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LobbyPlayerTableHandle`], which mediates access to the table `lobby_player`.
    fn lobby_player(&self) -> LobbyPlayerTableHandle<'_>;
}

impl LobbyPlayerTableAccess for super::RemoteTables {
    fn lobby_player(&self) -> LobbyPlayerTableHandle<'_> {
        LobbyPlayerTableHandle {
            imp: self.imp.get_table::<LobbyPlayer>("lobby_player"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LobbyPlayerInsertCallbackId(__sdk::CallbackId);
pub struct LobbyPlayerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LobbyPlayerTableHandle<'ctx> {
    type Row = LobbyPlayer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LobbyPlayer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LobbyPlayerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LobbyPlayerInsertCallbackId {
        LobbyPlayerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LobbyPlayerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LobbyPlayerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LobbyPlayerDeleteCallbackId {
        LobbyPlayerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LobbyPlayerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LobbyPlayer>("lobby_player");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct LobbyPlayerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LobbyPlayerTableHandle<'ctx> {
    type UpdateCallbackId = LobbyPlayerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LobbyPlayerUpdateCallbackId {
        LobbyPlayerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LobbyPlayerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<LobbyPlayer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LobbyPlayer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `lobby_player`,
/// which allows point queries on the field of the same name
/// via the [`LobbyPlayerIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.lobby_player().id().find(...)`.
pub struct LobbyPlayerIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LobbyPlayer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LobbyPlayerTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `lobby_player`.
    pub fn id(&self) -> LobbyPlayerIdUnique<'ctx> {
        LobbyPlayerIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LobbyPlayerIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<LobbyPlayer> {
        self.imp.find(col_val)
    }
}
