// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::lobby_secret_type::LobbySecret;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `lobby_secret`.
///
/// Obtain a handle from the [`LobbySecretTableAccess::lobby_secret`] method on [`super::RemoteTables`],
/// like `ctx.db.lobby_secret()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.lobby_secret().on_insert(...)`.
pub struct LobbySecretTableHandle<'ctx> {
    imp: __sdk::TableHandle<LobbySecret>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `lobby_secret`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LobbySecretTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LobbySecretTableHandle`], which mediates access to the table `lobby_secret`.
    fn lobby_secret(&self) -> LobbySecretTableHandle<'_>;
}

impl LobbySecretTableAccess for super::RemoteTables {
    fn lobby_secret(&self) -> LobbySecretTableHandle<'_> {
        LobbySecretTableHandle {
            imp: self.imp.get_table::<LobbySecret>("lobby_secret"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LobbySecretInsertCallbackId(__sdk::CallbackId);
pub struct LobbySecretDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LobbySecretTableHandle<'ctx> {
    type Row = LobbySecret;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LobbySecret> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LobbySecretInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LobbySecretInsertCallbackId {
        LobbySecretInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LobbySecretInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LobbySecretDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LobbySecretDeleteCallbackId {
        LobbySecretDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LobbySecretDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LobbySecret>("lobby_secret");
    _table.add_unique_constraint::<u64>("lobby_id", |row| &row.lobby_id);
}
pub struct LobbySecretUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LobbySecretTableHandle<'ctx> {
    type UpdateCallbackId = LobbySecretUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LobbySecretUpdateCallbackId {
        LobbySecretUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LobbySecretUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<LobbySecret>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LobbySecret>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `lobby_id` unique index on the table `lobby_secret`,
/// which allows point queries on the field of the same name
/// via the [`LobbySecretLobbyIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.lobby_secret().lobby_id().find(...)`.
pub struct LobbySecretLobbyIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LobbySecret, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LobbySecretTableHandle<'ctx> {
    /// Get a handle on the `lobby_id` unique index on the table `lobby_secret`.
    pub fn lobby_id(&self) -> LobbySecretLobbyIdUnique<'ctx> {
        LobbySecretLobbyIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("lobby_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LobbySecretLobbyIdUnique<'ctx> {
    /// Find the subscribed row whose `lobby_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<LobbySecret> {
        self.imp.find(col_val)
    }
}
