// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::friendly_fire_type::FriendlyFire;
use super::game_mode_type::GameMode;
use super::game_state_type::GameState;
use super::map_id_type::MapId;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Lobby {
    pub id: u64,
    pub name: String,
    pub host_id: __sdk::Identity,
    pub map_id: MapId,
    pub map_width: u32,
    pub map_height: u32,
    pub physics_world_id: u64,
    pub max_players: u8,
    pub game_state: GameState,
    pub game_mode: GameMode,
    pub created_at: __sdk::Timestamp,
    pub score_limit: i32,
    pub flag_limit: i32,
    pub time_limit_seconds: i32,
    pub has_password: bool,
    pub friendly_fire: FriendlyFire,
}

impl __sdk::InModule for Lobby {
    type Module = super::RemoteModule;
}
