// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LobbyPlayer {
    pub id: u64,
    pub lobby_id: u64,
    pub player_identity: __sdk::Identity,
    pub name: String,
    pub team: i32,
    pub is_ready: bool,
    pub joined_at: __sdk::Timestamp,
}

impl __sdk::InModule for LobbyPlayer {
    type Module = super::RemoteModule;
}
