// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::map_spawn_point_type::MapSpawnPoint;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `map_spawn_point`.
///
/// Obtain a handle from the [`MapSpawnPointTableAccess::map_spawn_point`] method on [`super::RemoteTables`],
/// like `ctx.db.map_spawn_point()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_spawn_point().on_insert(...)`.
pub struct MapSpawnPointTableHandle<'ctx> {
    imp: __sdk::TableHandle<MapSpawnPoint>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `map_spawn_point`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MapSpawnPointTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MapSpawnPointTableHandle`], which mediates access to the table `map_spawn_point`.
    fn map_spawn_point(&self) -> MapSpawnPointTableHandle<'_>;
}

impl MapSpawnPointTableAccess for super::RemoteTables {
    fn map_spawn_point(&self) -> MapSpawnPointTableHandle<'_> {
        MapSpawnPointTableHandle {
            imp: self.imp.get_table::<MapSpawnPoint>("map_spawn_point"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MapSpawnPointInsertCallbackId(__sdk::CallbackId);
pub struct MapSpawnPointDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MapSpawnPointTableHandle<'ctx> {
    type Row = MapSpawnPoint;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MapSpawnPoint> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MapSpawnPointInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapSpawnPointInsertCallbackId {
        MapSpawnPointInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MapSpawnPointInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MapSpawnPointDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapSpawnPointDeleteCallbackId {
        MapSpawnPointDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MapSpawnPointDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MapSpawnPoint>("map_spawn_point");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct MapSpawnPointUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MapSpawnPointTableHandle<'ctx> {
    type UpdateCallbackId = MapSpawnPointUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MapSpawnPointUpdateCallbackId {
        MapSpawnPointUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MapSpawnPointUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<MapSpawnPoint>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MapSpawnPoint>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `map_spawn_point`,
/// which allows point queries on the field of the same name
/// via the [`MapSpawnPointIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_spawn_point().id().find(...)`.
pub struct MapSpawnPointIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MapSpawnPoint, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MapSpawnPointTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `map_spawn_point`.
    pub fn id(&self) -> MapSpawnPointIdUnique<'ctx> {
        MapSpawnPointIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MapSpawnPointIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MapSpawnPoint> {
        self.imp.find(col_val)
    }
}
