// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::map_wall_type::MapWall;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `map_wall`.
///
/// Obtain a handle from the [`MapWallTableAccess::map_wall`] method on [`super::RemoteTables`],
/// like `ctx.db.map_wall()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_wall().on_insert(...)`.
pub struct MapWallTableHandle<'ctx> {
    imp: __sdk::TableHandle<MapWall>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `map_wall`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MapWallTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MapWallTableHandle`], which mediates access to the table `map_wall`.
    fn map_wall(&self) -> MapWallTableHandle<'_>;
}

impl MapWallTableAccess for super::RemoteTables {
    fn map_wall(&self) -> MapWallTableHandle<'_> {
        MapWallTableHandle {
            imp: self.imp.get_table::<MapWall>("map_wall"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MapWallInsertCallbackId(__sdk::CallbackId);
pub struct MapWallDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MapWallTableHandle<'ctx> {
    type Row = MapWall;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MapWall> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MapWallInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapWallInsertCallbackId {
        MapWallInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MapWallInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MapWallDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapWallDeleteCallbackId {
        MapWallDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MapWallDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MapWall>("map_wall");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct MapWallUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MapWallTableHandle<'ctx> {
    type UpdateCallbackId = MapWallUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MapWallUpdateCallbackId {
        MapWallUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MapWallUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<MapWall>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MapWall>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `map_wall`,
/// which allows point queries on the field of the same name
/// via the [`MapWallIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_wall().id().find(...)`.
pub struct MapWallIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MapWall, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MapWallTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `map_wall`.
    pub fn id(&self) -> MapWallIdUnique<'ctx> {
        MapWallIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MapWallIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MapWall> {
        self.imp.find(col_val)
    }
}
