// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::map_flag_location_type::MapFlagLocation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `map_flag_location`.
///
/// Obtain a handle from the [`MapFlagLocationTableAccess::map_flag_location`] method on [`super::RemoteTables`],
/// like `ctx.db.map_flag_location()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_flag_location().on_insert(...)`.
pub struct MapFlagLocationTableHandle<'ctx> {
    imp: __sdk::TableHandle<MapFlagLocation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `map_flag_location`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MapFlagLocationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MapFlagLocationTableHandle`], which mediates access to the table `map_flag_location`.
    fn map_flag_location(&self) -> MapFlagLocationTableHandle<'_>;
}

impl MapFlagLocationTableAccess for super::RemoteTables {
    fn map_flag_location(&self) -> MapFlagLocationTableHandle<'_> {
        MapFlagLocationTableHandle {
            imp: self.imp.get_table::<MapFlagLocation>("map_flag_location"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MapFlagLocationInsertCallbackId(__sdk::CallbackId);
pub struct MapFlagLocationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MapFlagLocationTableHandle<'ctx> {
    type Row = MapFlagLocation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MapFlagLocation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MapFlagLocationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapFlagLocationInsertCallbackId {
        MapFlagLocationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MapFlagLocationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MapFlagLocationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapFlagLocationDeleteCallbackId {
        MapFlagLocationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MapFlagLocationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MapFlagLocation>("map_flag_location");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct MapFlagLocationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MapFlagLocationTableHandle<'ctx> {
    type UpdateCallbackId = MapFlagLocationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MapFlagLocationUpdateCallbackId {
        MapFlagLocationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MapFlagLocationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<MapFlagLocation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MapFlagLocation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `map_flag_location`,
/// which allows point queries on the field of the same name
/// via the [`MapFlagLocationIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map_flag_location().id().find(...)`.
pub struct MapFlagLocationIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MapFlagLocation, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MapFlagLocationTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `map_flag_location`.
    pub fn id(&self) -> MapFlagLocationIdUnique<'ctx> {
        MapFlagLocationIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MapFlagLocationIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MapFlagLocation> {
        self.imp.find(col_val)
    }
}
