// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.11.3 (commit 02449737ca3b29e7e39679fccbef541a50f32094).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod client_connected_reducer;
pub mod client_disconnected_reducer;
pub mod collider_type;
pub mod collider_type_type;
pub mod create_lobby_reducer;
pub mod damage_zone_table;
pub mod damage_zone_type;
pub mod debug_collision_bodies_reducer;
pub mod debug_photon_beam_target_table;
pub mod debug_photon_beam_target_type;
pub mod debug_physics_world_reducer;
pub mod debug_player_in_wall_reducer;
pub mod detonate_rocket_reducer;
pub mod end_game_reducer;
pub mod friendly_fire_type;
pub mod game_config_table;
pub mod game_config_type;
pub mod game_mode_type;
pub mod game_state_type;
pub mod grenade_table;
pub mod grenade_type;
pub mod join_lobby_reducer;
pub mod kill_event_table;
pub mod kill_event_type;
pub mod leave_lobby_reducer;
pub mod lobby_player_table;
pub mod lobby_player_type;
pub mod lobby_secret_table;
pub mod lobby_secret_type;
pub mod lobby_table;
pub mod lobby_type;
pub mod map_flag_location_table;
pub mod map_flag_location_type;
pub mod map_id_type;
pub mod map_spawn_point_table;
pub mod map_spawn_point_type;
pub mod map_wall_table;
pub mod map_wall_type;
pub mod pending_photon_beam_table;
pub mod pending_photon_beam_type;
pub mod photon_beam_table;
pub mod photon_beam_type;
pub mod photon_rifle_charge_table;
pub mod photon_rifle_charge_type;
pub mod physics_tick_heartbeat_table;
pub mod physics_tick_heartbeat_type;
pub mod physics_tick_reducer;
pub mod physics_tick_timer_table;
pub mod physics_tick_timer_type;
pub mod physics_world_type;
pub mod player_table;
pub mod player_type;
pub mod projectile_table;
pub mod projectile_type;
pub mod rapier_collider_table;
pub mod rapier_physics_world_table;
pub mod rapier_raycast_table;
pub mod rapier_rigid_body_properties_table;
pub mod rapier_rigid_body_table;
pub mod rapier_sensor_collision_table;
pub mod rapier_trigger_table;
pub mod ray_cast_hit_type;
pub mod ray_cast_type;
pub mod request_spawn_reducer;
pub mod rigid_body_properties_type;
pub mod rigid_body_type;
pub mod rigid_body_type_type;
pub mod secondary_type_type;
pub mod sensor_collision_type;
pub mod set_loadout_reducer;
pub mod set_marble_config_reducer;
pub mod set_player_color_reducer;
pub mod set_ready_reducer;
pub mod set_shooting_reducer;
pub mod shoot_reducer;
pub mod start_game_reducer;
pub mod throw_grenade_reducer;
pub mod throw_molotov_reducer;
pub mod trigger_type;
pub mod update_input_reducer;
pub mod use_secondary_reducer;
pub mod weapon_type_type;

pub use client_connected_reducer::{
    client_connected, set_flags_for_client_connected, ClientConnectedCallbackId,
};
pub use client_disconnected_reducer::{
    client_disconnected, set_flags_for_client_disconnected, ClientDisconnectedCallbackId,
};
pub use collider_type::Collider;
pub use collider_type_type::ColliderType;
pub use create_lobby_reducer::{create_lobby, set_flags_for_create_lobby, CreateLobbyCallbackId};
pub use damage_zone_table::*;
pub use damage_zone_type::DamageZone;
pub use debug_collision_bodies_reducer::{
    debug_collision_bodies, set_flags_for_debug_collision_bodies, DebugCollisionBodiesCallbackId,
};
pub use debug_photon_beam_target_table::*;
pub use debug_photon_beam_target_type::DebugPhotonBeamTarget;
pub use debug_physics_world_reducer::{
    debug_physics_world, set_flags_for_debug_physics_world, DebugPhysicsWorldCallbackId,
};
pub use debug_player_in_wall_reducer::{
    debug_player_in_wall, set_flags_for_debug_player_in_wall, DebugPlayerInWallCallbackId,
};
pub use detonate_rocket_reducer::{
    detonate_rocket, set_flags_for_detonate_rocket, DetonateRocketCallbackId,
};
pub use end_game_reducer::{end_game, set_flags_for_end_game, EndGameCallbackId};
pub use friendly_fire_type::FriendlyFire;
pub use game_config_table::*;
pub use game_config_type::GameConfig;
pub use game_mode_type::GameMode;
pub use game_state_type::GameState;
pub use grenade_table::*;
pub use grenade_type::Grenade;
pub use join_lobby_reducer::{join_lobby, set_flags_for_join_lobby, JoinLobbyCallbackId};
pub use kill_event_table::*;
pub use kill_event_type::KillEvent;
pub use leave_lobby_reducer::{leave_lobby, set_flags_for_leave_lobby, LeaveLobbyCallbackId};
pub use lobby_player_table::*;
pub use lobby_player_type::LobbyPlayer;
pub use lobby_secret_table::*;
pub use lobby_secret_type::LobbySecret;
pub use lobby_table::*;
pub use lobby_type::Lobby;
pub use map_flag_location_table::*;
pub use map_flag_location_type::MapFlagLocation;
pub use map_id_type::MapId;
pub use map_spawn_point_table::*;
pub use map_spawn_point_type::MapSpawnPoint;
pub use map_wall_table::*;
pub use map_wall_type::MapWall;
pub use pending_photon_beam_table::*;
pub use pending_photon_beam_type::PendingPhotonBeam;
pub use photon_beam_table::*;
pub use photon_beam_type::PhotonBeam;
pub use photon_rifle_charge_table::*;
pub use photon_rifle_charge_type::PhotonRifleCharge;
pub use physics_tick_heartbeat_table::*;
pub use physics_tick_heartbeat_type::PhysicsTickHeartbeat;
pub use physics_tick_reducer::{physics_tick, set_flags_for_physics_tick, PhysicsTickCallbackId};
pub use physics_tick_timer_table::*;
pub use physics_tick_timer_type::PhysicsTickTimer;
pub use physics_world_type::PhysicsWorld;
pub use player_table::*;
pub use player_type::Player;
pub use projectile_table::*;
pub use projectile_type::Projectile;
pub use rapier_collider_table::*;
pub use rapier_physics_world_table::*;
pub use rapier_raycast_table::*;
pub use rapier_rigid_body_properties_table::*;
pub use rapier_rigid_body_table::*;
pub use rapier_sensor_collision_table::*;
pub use rapier_trigger_table::*;
pub use ray_cast_hit_type::RayCastHit;
pub use ray_cast_type::RayCast;
pub use request_spawn_reducer::{
    request_spawn, set_flags_for_request_spawn, RequestSpawnCallbackId,
};
pub use rigid_body_properties_type::RigidBodyProperties;
pub use rigid_body_type::RigidBody;
pub use rigid_body_type_type::RigidBodyType;
pub use secondary_type_type::SecondaryType;
pub use sensor_collision_type::SensorCollision;
pub use set_loadout_reducer::{set_flags_for_set_loadout, set_loadout, SetLoadoutCallbackId};
pub use set_marble_config_reducer::{
    set_flags_for_set_marble_config, set_marble_config, SetMarbleConfigCallbackId,
};
pub use set_player_color_reducer::{
    set_flags_for_set_player_color, set_player_color, SetPlayerColorCallbackId,
};
pub use set_ready_reducer::{set_flags_for_set_ready, set_ready, SetReadyCallbackId};
pub use set_shooting_reducer::{set_flags_for_set_shooting, set_shooting, SetShootingCallbackId};
pub use shoot_reducer::{set_flags_for_shoot, shoot, ShootCallbackId};
pub use start_game_reducer::{set_flags_for_start_game, start_game, StartGameCallbackId};
pub use throw_grenade_reducer::{
    set_flags_for_throw_grenade, throw_grenade, ThrowGrenadeCallbackId,
};
pub use throw_molotov_reducer::{
    set_flags_for_throw_molotov, throw_molotov, ThrowMolotovCallbackId,
};
pub use trigger_type::Trigger;
pub use update_input_reducer::{set_flags_for_update_input, update_input, UpdateInputCallbackId};
pub use use_secondary_reducer::{
    set_flags_for_use_secondary, use_secondary, UseSecondaryCallbackId,
};
pub use weapon_type_type::WeaponType;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    ClientConnected,
    ClientDisconnected,
    CreateLobby {
        name: String,
        map_id: MapId,
        game_mode: GameMode,
        max_players: u8,
        score_limit: i32,
        password: String,
        custom_map_json: String,
    },
    DebugCollisionBodies {
        world_id: u64,
    },
    DebugPhysicsWorld {
        world_id: u64,
    },
    DebugPlayerInWall {
        player_identity: __sdk::Identity,
    },
    DetonateRocket,
    EndGame {
        lobby_id: u64,
    },
    JoinLobby {
        lobby_id: u64,
        player_name: String,
        password: String,
    },
    LeaveLobby,
    PhysicsTick {
        timer: PhysicsTickTimer,
    },
    RequestSpawn {
        weapon: WeaponType,
        secondary: SecondaryType,
    },
    SetLoadout {
        weapon: WeaponType,
        secondary: SecondaryType,
    },
    SetMarbleConfig {
        design_id: u8,
        main_r: f32,
        main_g: f32,
        main_b: f32,
        sec_r: f32,
        sec_g: f32,
        sec_b: f32,
    },
    SetPlayerColor {
        r: f32,
        g: f32,
        b: f32,
    },
    SetReady {
        ready: bool,
    },
    SetShooting {
        is_shooting: bool,
        aim_x: f32,
        aim_z: f32,
    },
    Shoot,
    StartGame,
    ThrowGrenade {
        aim_x: f32,
        aim_z: f32,
    },
    ThrowMolotov {
        aim_x: f32,
        aim_z: f32,
    },
    UpdateInput {
        input_x: f32,
        input_z: f32,
        aim_x: f32,
        aim_z: f32,
    },
    UseSecondary,
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::ClientConnected => "client_connected",
            Reducer::ClientDisconnected => "client_disconnected",
            Reducer::CreateLobby { .. } => "create_lobby",
            Reducer::DebugCollisionBodies { .. } => "debug_collision_bodies",
            Reducer::DebugPhysicsWorld { .. } => "debug_physics_world",
            Reducer::DebugPlayerInWall { .. } => "debug_player_in_wall",
            Reducer::DetonateRocket => "detonate_rocket",
            Reducer::EndGame { .. } => "end_game",
            Reducer::JoinLobby { .. } => "join_lobby",
            Reducer::LeaveLobby => "leave_lobby",
            Reducer::PhysicsTick { .. } => "physics_tick",
            Reducer::RequestSpawn { .. } => "request_spawn",
            Reducer::SetLoadout { .. } => "set_loadout",
            Reducer::SetMarbleConfig { .. } => "set_marble_config",
            Reducer::SetPlayerColor { .. } => "set_player_color",
            Reducer::SetReady { .. } => "set_ready",
            Reducer::SetShooting { .. } => "set_shooting",
            Reducer::Shoot => "shoot",
            Reducer::StartGame => "start_game",
            Reducer::ThrowGrenade { .. } => "throw_grenade",
            Reducer::ThrowMolotov { .. } => "throw_molotov",
            Reducer::UpdateInput { .. } => "update_input",
            Reducer::UseSecondary => "use_secondary",
            _ => unreachable!(),
        }
    }
}
impl TryFrom<__ws::ReducerCallInfo<__ws::BsatnFormat>> for Reducer {
    type Error = __sdk::Error;
    fn try_from(value: __ws::ReducerCallInfo<__ws::BsatnFormat>) -> __sdk::Result<Self> {
        match &value.reducer_name[..] {
            "client_connected" => Ok(__sdk::parse_reducer_args::<
                client_connected_reducer::ClientConnectedArgs,
            >("client_connected", &value.args)?
            .into()),
            "client_disconnected" => Ok(__sdk::parse_reducer_args::<
                client_disconnected_reducer::ClientDisconnectedArgs,
            >("client_disconnected", &value.args)?
            .into()),
            "create_lobby" => Ok(
                __sdk::parse_reducer_args::<create_lobby_reducer::CreateLobbyArgs>(
                    "create_lobby",
                    &value.args,
                )?
                .into(),
            ),
            "debug_collision_bodies" => Ok(__sdk::parse_reducer_args::<
                debug_collision_bodies_reducer::DebugCollisionBodiesArgs,
            >("debug_collision_bodies", &value.args)?
            .into()),
            "debug_physics_world" => Ok(__sdk::parse_reducer_args::<
                debug_physics_world_reducer::DebugPhysicsWorldArgs,
            >("debug_physics_world", &value.args)?
            .into()),
            "debug_player_in_wall" => Ok(__sdk::parse_reducer_args::<
                debug_player_in_wall_reducer::DebugPlayerInWallArgs,
            >("debug_player_in_wall", &value.args)?
            .into()),
            "detonate_rocket" => Ok(__sdk::parse_reducer_args::<
                detonate_rocket_reducer::DetonateRocketArgs,
            >("detonate_rocket", &value.args)?
            .into()),
            "end_game" => Ok(__sdk::parse_reducer_args::<end_game_reducer::EndGameArgs>(
                "end_game",
                &value.args,
            )?
            .into()),
            "join_lobby" => Ok(
                __sdk::parse_reducer_args::<join_lobby_reducer::JoinLobbyArgs>(
                    "join_lobby",
                    &value.args,
                )?
                .into(),
            ),
            "leave_lobby" => Ok(
                __sdk::parse_reducer_args::<leave_lobby_reducer::LeaveLobbyArgs>(
                    "leave_lobby",
                    &value.args,
                )?
                .into(),
            ),
            "physics_tick" => Ok(
                __sdk::parse_reducer_args::<physics_tick_reducer::PhysicsTickArgs>(
                    "physics_tick",
                    &value.args,
                )?
                .into(),
            ),
            "request_spawn" => Ok(__sdk::parse_reducer_args::<
                request_spawn_reducer::RequestSpawnArgs,
            >("request_spawn", &value.args)?
            .into()),
            "set_loadout" => Ok(
                __sdk::parse_reducer_args::<set_loadout_reducer::SetLoadoutArgs>(
                    "set_loadout",
                    &value.args,
                )?
                .into(),
            ),
            "set_marble_config" => Ok(__sdk::parse_reducer_args::<
                set_marble_config_reducer::SetMarbleConfigArgs,
            >("set_marble_config", &value.args)?
            .into()),
            "set_player_color" => Ok(__sdk::parse_reducer_args::<
                set_player_color_reducer::SetPlayerColorArgs,
            >("set_player_color", &value.args)?
            .into()),
            "set_ready" => Ok(
                __sdk::parse_reducer_args::<set_ready_reducer::SetReadyArgs>(
                    "set_ready",
                    &value.args,
                )?
                .into(),
            ),
            "set_shooting" => Ok(
                __sdk::parse_reducer_args::<set_shooting_reducer::SetShootingArgs>(
                    "set_shooting",
                    &value.args,
                )?
                .into(),
            ),
            "shoot" => Ok(__sdk::parse_reducer_args::<shoot_reducer::ShootArgs>(
                "shoot",
                &value.args,
            )?
            .into()),
            "start_game" => Ok(
                __sdk::parse_reducer_args::<start_game_reducer::StartGameArgs>(
                    "start_game",
                    &value.args,
                )?
                .into(),
            ),
            "throw_grenade" => Ok(__sdk::parse_reducer_args::<
                throw_grenade_reducer::ThrowGrenadeArgs,
            >("throw_grenade", &value.args)?
            .into()),
            "throw_molotov" => Ok(__sdk::parse_reducer_args::<
                throw_molotov_reducer::ThrowMolotovArgs,
            >("throw_molotov", &value.args)?
            .into()),
            "update_input" => Ok(
                __sdk::parse_reducer_args::<update_input_reducer::UpdateInputArgs>(
                    "update_input",
                    &value.args,
                )?
                .into(),
            ),
            "use_secondary" => Ok(__sdk::parse_reducer_args::<
                use_secondary_reducer::UseSecondaryArgs,
            >("use_secondary", &value.args)?
            .into()),
            unknown => {
                Err(
                    __sdk::InternalError::unknown_name("reducer", unknown, "ReducerCallInfo")
                        .into(),
                )
            }
        }
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    damage_zone: __sdk::TableUpdate<DamageZone>,
    debug_photon_beam_target: __sdk::TableUpdate<DebugPhotonBeamTarget>,
    game_config: __sdk::TableUpdate<GameConfig>,
    grenade: __sdk::TableUpdate<Grenade>,
    kill_event: __sdk::TableUpdate<KillEvent>,
    lobby: __sdk::TableUpdate<Lobby>,
    lobby_player: __sdk::TableUpdate<LobbyPlayer>,
    lobby_secret: __sdk::TableUpdate<LobbySecret>,
    map_flag_location: __sdk::TableUpdate<MapFlagLocation>,
    map_spawn_point: __sdk::TableUpdate<MapSpawnPoint>,
    map_wall: __sdk::TableUpdate<MapWall>,
    pending_photon_beam: __sdk::TableUpdate<PendingPhotonBeam>,
    photon_beam: __sdk::TableUpdate<PhotonBeam>,
    photon_rifle_charge: __sdk::TableUpdate<PhotonRifleCharge>,
    physics_tick_heartbeat: __sdk::TableUpdate<PhysicsTickHeartbeat>,
    physics_tick_timer: __sdk::TableUpdate<PhysicsTickTimer>,
    player: __sdk::TableUpdate<Player>,
    projectile: __sdk::TableUpdate<Projectile>,
    rapier_collider: __sdk::TableUpdate<Collider>,
    rapier_physics_world: __sdk::TableUpdate<PhysicsWorld>,
    rapier_raycast: __sdk::TableUpdate<RayCast>,
    rapier_rigid_body: __sdk::TableUpdate<RigidBody>,
    rapier_rigid_body_properties: __sdk::TableUpdate<RigidBodyProperties>,
    rapier_sensor_collision: __sdk::TableUpdate<SensorCollision>,
    rapier_trigger: __sdk::TableUpdate<Trigger>,
}

impl TryFrom<__ws::DatabaseUpdate<__ws::BsatnFormat>> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::DatabaseUpdate<__ws::BsatnFormat>) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in raw.tables {
            match &table_update.table_name[..] {
                "damage_zone" => db_update
                    .damage_zone
                    .append(damage_zone_table::parse_table_update(table_update)?),
                "debug_photon_beam_target" => db_update.debug_photon_beam_target.append(
                    debug_photon_beam_target_table::parse_table_update(table_update)?,
                ),
                "game_config" => db_update
                    .game_config
                    .append(game_config_table::parse_table_update(table_update)?),
                "grenade" => db_update
                    .grenade
                    .append(grenade_table::parse_table_update(table_update)?),
                "kill_event" => db_update
                    .kill_event
                    .append(kill_event_table::parse_table_update(table_update)?),
                "lobby" => db_update
                    .lobby
                    .append(lobby_table::parse_table_update(table_update)?),
                "lobby_player" => db_update
                    .lobby_player
                    .append(lobby_player_table::parse_table_update(table_update)?),
                "lobby_secret" => db_update
                    .lobby_secret
                    .append(lobby_secret_table::parse_table_update(table_update)?),
                "map_flag_location" => db_update
                    .map_flag_location
                    .append(map_flag_location_table::parse_table_update(table_update)?),
                "map_spawn_point" => db_update
                    .map_spawn_point
                    .append(map_spawn_point_table::parse_table_update(table_update)?),
                "map_wall" => db_update
                    .map_wall
                    .append(map_wall_table::parse_table_update(table_update)?),
                "pending_photon_beam" => db_update
                    .pending_photon_beam
                    .append(pending_photon_beam_table::parse_table_update(table_update)?),
                "photon_beam" => db_update
                    .photon_beam
                    .append(photon_beam_table::parse_table_update(table_update)?),
                "photon_rifle_charge" => db_update
                    .photon_rifle_charge
                    .append(photon_rifle_charge_table::parse_table_update(table_update)?),
                "physics_tick_heartbeat" => db_update.physics_tick_heartbeat.append(
                    physics_tick_heartbeat_table::parse_table_update(table_update)?,
                ),
                "physics_tick_timer" => db_update
                    .physics_tick_timer
                    .append(physics_tick_timer_table::parse_table_update(table_update)?),
                "player" => db_update
                    .player
                    .append(player_table::parse_table_update(table_update)?),
                "projectile" => db_update
                    .projectile
                    .append(projectile_table::parse_table_update(table_update)?),
                "rapier_collider" => db_update
                    .rapier_collider
                    .append(rapier_collider_table::parse_table_update(table_update)?),
                "rapier_physics_world" => db_update.rapier_physics_world.append(
                    rapier_physics_world_table::parse_table_update(table_update)?,
                ),
                "rapier_raycast" => db_update
                    .rapier_raycast
                    .append(rapier_raycast_table::parse_table_update(table_update)?),
                "rapier_rigid_body" => db_update
                    .rapier_rigid_body
                    .append(rapier_rigid_body_table::parse_table_update(table_update)?),
                "rapier_rigid_body_properties" => db_update.rapier_rigid_body_properties.append(
                    rapier_rigid_body_properties_table::parse_table_update(table_update)?,
                ),
                "rapier_sensor_collision" => db_update.rapier_sensor_collision.append(
                    rapier_sensor_collision_table::parse_table_update(table_update)?,
                ),
                "rapier_trigger" => db_update
                    .rapier_trigger
                    .append(rapier_trigger_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.damage_zone = cache
            .apply_diff_to_table::<DamageZone>("damage_zone", &self.damage_zone)
            .with_updates_by_pk(|row| &row.trigger_id);
        diff.debug_photon_beam_target = cache
            .apply_diff_to_table::<DebugPhotonBeamTarget>(
                "debug_photon_beam_target",
                &self.debug_photon_beam_target,
            )
            .with_updates_by_pk(|row| &row.identity);
        diff.game_config = cache
            .apply_diff_to_table::<GameConfig>("game_config", &self.game_config)
            .with_updates_by_pk(|row| &row.id);
        diff.grenade = cache
            .apply_diff_to_table::<Grenade>("grenade", &self.grenade)
            .with_updates_by_pk(|row| &row.rigid_body_id);
        diff.kill_event = cache
            .apply_diff_to_table::<KillEvent>("kill_event", &self.kill_event)
            .with_updates_by_pk(|row| &row.id);
        diff.lobby = cache
            .apply_diff_to_table::<Lobby>("lobby", &self.lobby)
            .with_updates_by_pk(|row| &row.id);
        diff.lobby_player = cache
            .apply_diff_to_table::<LobbyPlayer>("lobby_player", &self.lobby_player)
            .with_updates_by_pk(|row| &row.id);
        diff.lobby_secret = cache
            .apply_diff_to_table::<LobbySecret>("lobby_secret", &self.lobby_secret)
            .with_updates_by_pk(|row| &row.lobby_id);
        diff.map_flag_location = cache
            .apply_diff_to_table::<MapFlagLocation>("map_flag_location", &self.map_flag_location)
            .with_updates_by_pk(|row| &row.id);
        diff.map_spawn_point = cache
            .apply_diff_to_table::<MapSpawnPoint>("map_spawn_point", &self.map_spawn_point)
            .with_updates_by_pk(|row| &row.id);
        diff.map_wall = cache
            .apply_diff_to_table::<MapWall>("map_wall", &self.map_wall)
            .with_updates_by_pk(|row| &row.id);
        diff.pending_photon_beam = cache
            .apply_diff_to_table::<PendingPhotonBeam>(
                "pending_photon_beam",
                &self.pending_photon_beam,
            )
            .with_updates_by_pk(|row| &row.raycast_id);
        diff.photon_beam = cache
            .apply_diff_to_table::<PhotonBeam>("photon_beam", &self.photon_beam)
            .with_updates_by_pk(|row| &row.id);
        diff.photon_rifle_charge = cache
            .apply_diff_to_table::<PhotonRifleCharge>(
                "photon_rifle_charge",
                &self.photon_rifle_charge,
            )
            .with_updates_by_pk(|row| &row.identity);
        diff.physics_tick_heartbeat = cache
            .apply_diff_to_table::<PhysicsTickHeartbeat>(
                "physics_tick_heartbeat",
                &self.physics_tick_heartbeat,
            )
            .with_updates_by_pk(|row| &row.world_id);
        diff.physics_tick_timer = cache
            .apply_diff_to_table::<PhysicsTickTimer>("physics_tick_timer", &self.physics_tick_timer)
            .with_updates_by_pk(|row| &row.scheduled_id);
        diff.player = cache
            .apply_diff_to_table::<Player>("player", &self.player)
            .with_updates_by_pk(|row| &row.identity);
        diff.projectile = cache
            .apply_diff_to_table::<Projectile>("projectile", &self.projectile)
            .with_updates_by_pk(|row| &row.rigid_body_id);
        diff.rapier_collider = cache
            .apply_diff_to_table::<Collider>("rapier_collider", &self.rapier_collider)
            .with_updates_by_pk(|row| &row.id);
        diff.rapier_physics_world = cache
            .apply_diff_to_table::<PhysicsWorld>("rapier_physics_world", &self.rapier_physics_world)
            .with_updates_by_pk(|row| &row.id);
        diff.rapier_raycast = cache
            .apply_diff_to_table::<RayCast>("rapier_raycast", &self.rapier_raycast)
            .with_updates_by_pk(|row| &row.id);
        diff.rapier_rigid_body = cache
            .apply_diff_to_table::<RigidBody>("rapier_rigid_body", &self.rapier_rigid_body)
            .with_updates_by_pk(|row| &row.id);
        diff.rapier_rigid_body_properties = cache
            .apply_diff_to_table::<RigidBodyProperties>(
                "rapier_rigid_body_properties",
                &self.rapier_rigid_body_properties,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.rapier_sensor_collision = cache
            .apply_diff_to_table::<SensorCollision>(
                "rapier_sensor_collision",
                &self.rapier_sensor_collision,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.rapier_trigger = cache
            .apply_diff_to_table::<Trigger>("rapier_trigger", &self.rapier_trigger)
            .with_updates_by_pk(|row| &row.id);

        diff
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    damage_zone: __sdk::TableAppliedDiff<'r, DamageZone>,
    debug_photon_beam_target: __sdk::TableAppliedDiff<'r, DebugPhotonBeamTarget>,
    game_config: __sdk::TableAppliedDiff<'r, GameConfig>,
    grenade: __sdk::TableAppliedDiff<'r, Grenade>,
    kill_event: __sdk::TableAppliedDiff<'r, KillEvent>,
    lobby: __sdk::TableAppliedDiff<'r, Lobby>,
    lobby_player: __sdk::TableAppliedDiff<'r, LobbyPlayer>,
    lobby_secret: __sdk::TableAppliedDiff<'r, LobbySecret>,
    map_flag_location: __sdk::TableAppliedDiff<'r, MapFlagLocation>,
    map_spawn_point: __sdk::TableAppliedDiff<'r, MapSpawnPoint>,
    map_wall: __sdk::TableAppliedDiff<'r, MapWall>,
    pending_photon_beam: __sdk::TableAppliedDiff<'r, PendingPhotonBeam>,
    photon_beam: __sdk::TableAppliedDiff<'r, PhotonBeam>,
    photon_rifle_charge: __sdk::TableAppliedDiff<'r, PhotonRifleCharge>,
    physics_tick_heartbeat: __sdk::TableAppliedDiff<'r, PhysicsTickHeartbeat>,
    physics_tick_timer: __sdk::TableAppliedDiff<'r, PhysicsTickTimer>,
    player: __sdk::TableAppliedDiff<'r, Player>,
    projectile: __sdk::TableAppliedDiff<'r, Projectile>,
    rapier_collider: __sdk::TableAppliedDiff<'r, Collider>,
    rapier_physics_world: __sdk::TableAppliedDiff<'r, PhysicsWorld>,
    rapier_raycast: __sdk::TableAppliedDiff<'r, RayCast>,
    rapier_rigid_body: __sdk::TableAppliedDiff<'r, RigidBody>,
    rapier_rigid_body_properties: __sdk::TableAppliedDiff<'r, RigidBodyProperties>,
    rapier_sensor_collision: __sdk::TableAppliedDiff<'r, SensorCollision>,
    rapier_trigger: __sdk::TableAppliedDiff<'r, Trigger>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<DamageZone>("damage_zone", &self.damage_zone, event);
        callbacks.invoke_table_row_callbacks::<DebugPhotonBeamTarget>(
            "debug_photon_beam_target",
            &self.debug_photon_beam_target,
            event,
        );
        callbacks.invoke_table_row_callbacks::<GameConfig>("game_config", &self.game_config, event);
        callbacks.invoke_table_row_callbacks::<Grenade>("grenade", &self.grenade, event);
        callbacks.invoke_table_row_callbacks::<KillEvent>("kill_event", &self.kill_event, event);
        callbacks.invoke_table_row_callbacks::<Lobby>("lobby", &self.lobby, event);
        callbacks.invoke_table_row_callbacks::<LobbyPlayer>(
            "lobby_player",
            &self.lobby_player,
            event,
        );
        callbacks.invoke_table_row_callbacks::<LobbySecret>(
            "lobby_secret",
            &self.lobby_secret,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MapFlagLocation>(
            "map_flag_location",
            &self.map_flag_location,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MapSpawnPoint>(
            "map_spawn_point",
            &self.map_spawn_point,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MapWall>("map_wall", &self.map_wall, event);
        callbacks.invoke_table_row_callbacks::<PendingPhotonBeam>(
            "pending_photon_beam",
            &self.pending_photon_beam,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PhotonBeam>("photon_beam", &self.photon_beam, event);
        callbacks.invoke_table_row_callbacks::<PhotonRifleCharge>(
            "photon_rifle_charge",
            &self.photon_rifle_charge,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PhysicsTickHeartbeat>(
            "physics_tick_heartbeat",
            &self.physics_tick_heartbeat,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PhysicsTickTimer>(
            "physics_tick_timer",
            &self.physics_tick_timer,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Player>("player", &self.player, event);
        callbacks.invoke_table_row_callbacks::<Projectile>("projectile", &self.projectile, event);
        callbacks.invoke_table_row_callbacks::<Collider>(
            "rapier_collider",
            &self.rapier_collider,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PhysicsWorld>(
            "rapier_physics_world",
            &self.rapier_physics_world,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RayCast>(
            "rapier_raycast",
            &self.rapier_raycast,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RigidBody>(
            "rapier_rigid_body",
            &self.rapier_rigid_body,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RigidBodyProperties>(
            "rapier_rigid_body_properties",
            &self.rapier_rigid_body_properties,
            event,
        );
        callbacks.invoke_table_row_callbacks::<SensorCollision>(
            "rapier_sensor_collision",
            &self.rapier_sensor_collision,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Trigger>(
            "rapier_trigger",
            &self.rapier_trigger,
            event,
        );
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

#[doc(hidden)]
/// The `set_reducer_flags` field of [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
/// Each method sets the flags for the reducer with the same name.
///
/// This type is currently unstable and may be removed without a major version bump.
pub struct SetReducerFlags {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for SetReducerFlags {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SetReducerFlags = SetReducerFlags,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SetReducerFlags = SetReducerFlags,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        damage_zone_table::register_table(client_cache);
        debug_photon_beam_target_table::register_table(client_cache);
        game_config_table::register_table(client_cache);
        grenade_table::register_table(client_cache);
        kill_event_table::register_table(client_cache);
        lobby_table::register_table(client_cache);
        lobby_player_table::register_table(client_cache);
        lobby_secret_table::register_table(client_cache);
        map_flag_location_table::register_table(client_cache);
        map_spawn_point_table::register_table(client_cache);
        map_wall_table::register_table(client_cache);
        pending_photon_beam_table::register_table(client_cache);
        photon_beam_table::register_table(client_cache);
        photon_rifle_charge_table::register_table(client_cache);
        physics_tick_heartbeat_table::register_table(client_cache);
        physics_tick_timer_table::register_table(client_cache);
        player_table::register_table(client_cache);
        projectile_table::register_table(client_cache);
        rapier_collider_table::register_table(client_cache);
        rapier_physics_world_table::register_table(client_cache);
        rapier_raycast_table::register_table(client_cache);
        rapier_rigid_body_table::register_table(client_cache);
        rapier_rigid_body_properties_table::register_table(client_cache);
        rapier_sensor_collision_table::register_table(client_cache);
        rapier_trigger_table::register_table(client_cache);
    }
}
