// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PendingExplosionRaycast {
    pub id: u64,
    pub raycast_id: u64,
    pub target_identity: __sdk::Identity,
    pub target_rigid_body_id: u64,
    pub center_x: f32,
    pub center_y: f32,
    pub center_z: f32,
    pub damage: f32,
    pub radius: f32,
    pub source_id: __sdk::Identity,
    pub distance: f32,
}

impl __sdk::InModule for PendingExplosionRaycast {
    type Module = super::RemoteModule;
}
