// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::pending_explosion_raycast_type::PendingExplosionRaycast;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `pending_explosion_raycast`.
///
/// Obtain a handle from the [`PendingExplosionRaycastTableAccess::pending_explosion_raycast`] method on [`super::RemoteTables`],
/// like `ctx.db.pending_explosion_raycast()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pending_explosion_raycast().on_insert(...)`.
pub struct PendingExplosionRaycastTableHandle<'ctx> {
    imp: __sdk::TableHandle<PendingExplosionRaycast>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `pending_explosion_raycast`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PendingExplosionRaycastTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PendingExplosionRaycastTableHandle`], which mediates access to the table `pending_explosion_raycast`.
    fn pending_explosion_raycast(&self) -> PendingExplosionRaycastTableHandle<'_>;
}

impl PendingExplosionRaycastTableAccess for super::RemoteTables {
    fn pending_explosion_raycast(&self) -> PendingExplosionRaycastTableHandle<'_> {
        PendingExplosionRaycastTableHandle {
            imp: self
                .imp
                .get_table::<PendingExplosionRaycast>("pending_explosion_raycast"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PendingExplosionRaycastInsertCallbackId(__sdk::CallbackId);
pub struct PendingExplosionRaycastDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PendingExplosionRaycastTableHandle<'ctx> {
    type Row = PendingExplosionRaycast;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PendingExplosionRaycast> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PendingExplosionRaycastInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PendingExplosionRaycastInsertCallbackId {
        PendingExplosionRaycastInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PendingExplosionRaycastInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PendingExplosionRaycastDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PendingExplosionRaycastDeleteCallbackId {
        PendingExplosionRaycastDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PendingExplosionRaycastDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<PendingExplosionRaycast>("pending_explosion_raycast");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct PendingExplosionRaycastUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PendingExplosionRaycastTableHandle<'ctx> {
    type UpdateCallbackId = PendingExplosionRaycastUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PendingExplosionRaycastUpdateCallbackId {
        PendingExplosionRaycastUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PendingExplosionRaycastUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PendingExplosionRaycast>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PendingExplosionRaycast>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `pending_explosion_raycast`,
/// which allows point queries on the field of the same name
/// via the [`PendingExplosionRaycastIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pending_explosion_raycast().id().find(...)`.
pub struct PendingExplosionRaycastIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PendingExplosionRaycast, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PendingExplosionRaycastTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `pending_explosion_raycast`.
    pub fn id(&self) -> PendingExplosionRaycastIdUnique<'ctx> {
        PendingExplosionRaycastIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PendingExplosionRaycastIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PendingExplosionRaycast> {
        self.imp.find(col_val)
    }
}
