// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::pending_photon_beam_type::PendingPhotonBeam;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `pending_photon_beam`.
///
/// Obtain a handle from the [`PendingPhotonBeamTableAccess::pending_photon_beam`] method on [`super::RemoteTables`],
/// like `ctx.db.pending_photon_beam()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pending_photon_beam().on_insert(...)`.
pub struct PendingPhotonBeamTableHandle<'ctx> {
    imp: __sdk::TableHandle<PendingPhotonBeam>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `pending_photon_beam`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PendingPhotonBeamTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PendingPhotonBeamTableHandle`], which mediates access to the table `pending_photon_beam`.
    fn pending_photon_beam(&self) -> PendingPhotonBeamTableHandle<'_>;
}

impl PendingPhotonBeamTableAccess for super::RemoteTables {
    fn pending_photon_beam(&self) -> PendingPhotonBeamTableHandle<'_> {
        PendingPhotonBeamTableHandle {
            imp: self
                .imp
                .get_table::<PendingPhotonBeam>("pending_photon_beam"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PendingPhotonBeamInsertCallbackId(__sdk::CallbackId);
pub struct PendingPhotonBeamDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PendingPhotonBeamTableHandle<'ctx> {
    type Row = PendingPhotonBeam;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PendingPhotonBeam> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PendingPhotonBeamInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PendingPhotonBeamInsertCallbackId {
        PendingPhotonBeamInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PendingPhotonBeamInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PendingPhotonBeamDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PendingPhotonBeamDeleteCallbackId {
        PendingPhotonBeamDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PendingPhotonBeamDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PendingPhotonBeam>("pending_photon_beam");
    _table.add_unique_constraint::<u64>("raycast_id", |row| &row.raycast_id);
}
pub struct PendingPhotonBeamUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PendingPhotonBeamTableHandle<'ctx> {
    type UpdateCallbackId = PendingPhotonBeamUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PendingPhotonBeamUpdateCallbackId {
        PendingPhotonBeamUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PendingPhotonBeamUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PendingPhotonBeam>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PendingPhotonBeam>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `raycast_id` unique index on the table `pending_photon_beam`,
/// which allows point queries on the field of the same name
/// via the [`PendingPhotonBeamRaycastIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pending_photon_beam().raycast_id().find(...)`.
pub struct PendingPhotonBeamRaycastIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PendingPhotonBeam, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PendingPhotonBeamTableHandle<'ctx> {
    /// Get a handle on the `raycast_id` unique index on the table `pending_photon_beam`.
    pub fn raycast_id(&self) -> PendingPhotonBeamRaycastIdUnique<'ctx> {
        PendingPhotonBeamRaycastIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("raycast_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PendingPhotonBeamRaycastIdUnique<'ctx> {
    /// Find the subscribed row whose `raycast_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PendingPhotonBeam> {
        self.imp.find(col_val)
    }
}
