// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PhotonBeam {
    pub id: u64,
    pub owner_id: __sdk::Identity,
    pub origin_x: f32,
    pub origin_y: f32,
    pub origin_z: f32,
    pub end_x: f32,
    pub end_y: f32,
    pub end_z: f32,
    pub raycast_id: u64,
    pub trigger_id: u64,
    pub damage_per_tick: i32,
    pub remaining_ticks: i32,
    pub world_id: u64,
}

impl __sdk::InModule for PhotonBeam {
    type Module = super::RemoteModule;
}
