// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::photon_rifle_charge_type::PhotonRifleCharge;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `photon_rifle_charge`.
///
/// Obtain a handle from the [`PhotonRifleChargeTableAccess::photon_rifle_charge`] method on [`super::RemoteTables`],
/// like `ctx.db.photon_rifle_charge()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.photon_rifle_charge().on_insert(...)`.
pub struct PhotonRifleChargeTableHandle<'ctx> {
    imp: __sdk::TableHandle<PhotonRifleCharge>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `photon_rifle_charge`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PhotonRifleChargeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PhotonRifleChargeTableHandle`], which mediates access to the table `photon_rifle_charge`.
    fn photon_rifle_charge(&self) -> PhotonRifleChargeTableHandle<'_>;
}

impl PhotonRifleChargeTableAccess for super::RemoteTables {
    fn photon_rifle_charge(&self) -> PhotonRifleChargeTableHandle<'_> {
        PhotonRifleChargeTableHandle {
            imp: self
                .imp
                .get_table::<PhotonRifleCharge>("photon_rifle_charge"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PhotonRifleChargeInsertCallbackId(__sdk::CallbackId);
pub struct PhotonRifleChargeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PhotonRifleChargeTableHandle<'ctx> {
    type Row = PhotonRifleCharge;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PhotonRifleCharge> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PhotonRifleChargeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhotonRifleChargeInsertCallbackId {
        PhotonRifleChargeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PhotonRifleChargeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PhotonRifleChargeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhotonRifleChargeDeleteCallbackId {
        PhotonRifleChargeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PhotonRifleChargeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PhotonRifleCharge>("photon_rifle_charge");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}
pub struct PhotonRifleChargeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PhotonRifleChargeTableHandle<'ctx> {
    type UpdateCallbackId = PhotonRifleChargeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PhotonRifleChargeUpdateCallbackId {
        PhotonRifleChargeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PhotonRifleChargeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PhotonRifleCharge>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PhotonRifleCharge>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `identity` unique index on the table `photon_rifle_charge`,
/// which allows point queries on the field of the same name
/// via the [`PhotonRifleChargeIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.photon_rifle_charge().identity().find(...)`.
pub struct PhotonRifleChargeIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PhotonRifleCharge, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PhotonRifleChargeTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `photon_rifle_charge`.
    pub fn identity(&self) -> PhotonRifleChargeIdentityUnique<'ctx> {
        PhotonRifleChargeIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PhotonRifleChargeIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<PhotonRifleCharge> {
        self.imp.find(col_val)
    }
}
