// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::photon_beam_type::PhotonBeam;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `photon_beam`.
///
/// Obtain a handle from the [`PhotonBeamTableAccess::photon_beam`] method on [`super::RemoteTables`],
/// like `ctx.db.photon_beam()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.photon_beam().on_insert(...)`.
pub struct PhotonBeamTableHandle<'ctx> {
    imp: __sdk::TableHandle<PhotonBeam>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `photon_beam`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PhotonBeamTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PhotonBeamTableHandle`], which mediates access to the table `photon_beam`.
    fn photon_beam(&self) -> PhotonBeamTableHandle<'_>;
}

impl PhotonBeamTableAccess for super::RemoteTables {
    fn photon_beam(&self) -> PhotonBeamTableHandle<'_> {
        PhotonBeamTableHandle {
            imp: self.imp.get_table::<PhotonBeam>("photon_beam"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PhotonBeamInsertCallbackId(__sdk::CallbackId);
pub struct PhotonBeamDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PhotonBeamTableHandle<'ctx> {
    type Row = PhotonBeam;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PhotonBeam> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PhotonBeamInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhotonBeamInsertCallbackId {
        PhotonBeamInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PhotonBeamInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PhotonBeamDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhotonBeamDeleteCallbackId {
        PhotonBeamDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PhotonBeamDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PhotonBeam>("photon_beam");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct PhotonBeamUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PhotonBeamTableHandle<'ctx> {
    type UpdateCallbackId = PhotonBeamUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PhotonBeamUpdateCallbackId {
        PhotonBeamUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PhotonBeamUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PhotonBeam>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PhotonBeam>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `photon_beam`,
/// which allows point queries on the field of the same name
/// via the [`PhotonBeamIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.photon_beam().id().find(...)`.
pub struct PhotonBeamIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PhotonBeam, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PhotonBeamTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `photon_beam`.
    pub fn id(&self) -> PhotonBeamIdUnique<'ctx> {
        PhotonBeamIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PhotonBeamIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PhotonBeam> {
        self.imp.find(col_val)
    }
}
