// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::physics_tick_timer_type::PhysicsTickTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `physics_tick_timer`.
///
/// Obtain a handle from the [`PhysicsTickTimerTableAccess::physics_tick_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.physics_tick_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.physics_tick_timer().on_insert(...)`.
pub struct PhysicsTickTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<PhysicsTickTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `physics_tick_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PhysicsTickTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PhysicsTickTimerTableHandle`], which mediates access to the table `physics_tick_timer`.
    fn physics_tick_timer(&self) -> PhysicsTickTimerTableHandle<'_>;
}

impl PhysicsTickTimerTableAccess for super::RemoteTables {
    fn physics_tick_timer(&self) -> PhysicsTickTimerTableHandle<'_> {
        PhysicsTickTimerTableHandle {
            imp: self.imp.get_table::<PhysicsTickTimer>("physics_tick_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PhysicsTickTimerInsertCallbackId(__sdk::CallbackId);
pub struct PhysicsTickTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PhysicsTickTimerTableHandle<'ctx> {
    type Row = PhysicsTickTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PhysicsTickTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PhysicsTickTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhysicsTickTimerInsertCallbackId {
        PhysicsTickTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PhysicsTickTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PhysicsTickTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhysicsTickTimerDeleteCallbackId {
        PhysicsTickTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PhysicsTickTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PhysicsTickTimer>("physics_tick_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct PhysicsTickTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PhysicsTickTimerTableHandle<'ctx> {
    type UpdateCallbackId = PhysicsTickTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PhysicsTickTimerUpdateCallbackId {
        PhysicsTickTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PhysicsTickTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PhysicsTickTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PhysicsTickTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `physics_tick_timer`,
/// which allows point queries on the field of the same name
/// via the [`PhysicsTickTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.physics_tick_timer().scheduled_id().find(...)`.
pub struct PhysicsTickTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PhysicsTickTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PhysicsTickTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `physics_tick_timer`.
    pub fn scheduled_id(&self) -> PhysicsTickTimerScheduledIdUnique<'ctx> {
        PhysicsTickTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PhysicsTickTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PhysicsTickTimer> {
        self.imp.find(col_val)
    }
}
