// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PhysicsWorld {
    pub id: u64,
    pub ticks_per_second: f32,
    pub gravity_x: f32,
    pub gravity_y: f32,
    pub gravity_z: f32,
    pub num_solver_iterations: u32,
    pub num_additional_friction_iterations: u32,
    pub num_internal_pgs_iterations: u32,
    pub debug: bool,
}

impl __sdk::InModule for PhysicsWorld {
    type Module = super::RemoteModule;
}
