// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::physics_tick_heartbeat_type::PhysicsTickHeartbeat;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `physics_tick_heartbeat`.
///
/// Obtain a handle from the [`PhysicsTickHeartbeatTableAccess::physics_tick_heartbeat`] method on [`super::RemoteTables`],
/// like `ctx.db.physics_tick_heartbeat()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.physics_tick_heartbeat().on_insert(...)`.
pub struct PhysicsTickHeartbeatTableHandle<'ctx> {
    imp: __sdk::TableHandle<PhysicsTickHeartbeat>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `physics_tick_heartbeat`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PhysicsTickHeartbeatTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PhysicsTickHeartbeatTableHandle`], which mediates access to the table `physics_tick_heartbeat`.
    fn physics_tick_heartbeat(&self) -> PhysicsTickHeartbeatTableHandle<'_>;
}

impl PhysicsTickHeartbeatTableAccess for super::RemoteTables {
    fn physics_tick_heartbeat(&self) -> PhysicsTickHeartbeatTableHandle<'_> {
        PhysicsTickHeartbeatTableHandle {
            imp: self
                .imp
                .get_table::<PhysicsTickHeartbeat>("physics_tick_heartbeat"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PhysicsTickHeartbeatInsertCallbackId(__sdk::CallbackId);
pub struct PhysicsTickHeartbeatDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PhysicsTickHeartbeatTableHandle<'ctx> {
    type Row = PhysicsTickHeartbeat;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PhysicsTickHeartbeat> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PhysicsTickHeartbeatInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhysicsTickHeartbeatInsertCallbackId {
        PhysicsTickHeartbeatInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PhysicsTickHeartbeatInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PhysicsTickHeartbeatDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhysicsTickHeartbeatDeleteCallbackId {
        PhysicsTickHeartbeatDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PhysicsTickHeartbeatDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PhysicsTickHeartbeat>("physics_tick_heartbeat");
    _table.add_unique_constraint::<u64>("world_id", |row| &row.world_id);
}
pub struct PhysicsTickHeartbeatUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PhysicsTickHeartbeatTableHandle<'ctx> {
    type UpdateCallbackId = PhysicsTickHeartbeatUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PhysicsTickHeartbeatUpdateCallbackId {
        PhysicsTickHeartbeatUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PhysicsTickHeartbeatUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PhysicsTickHeartbeat>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PhysicsTickHeartbeat>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `world_id` unique index on the table `physics_tick_heartbeat`,
/// which allows point queries on the field of the same name
/// via the [`PhysicsTickHeartbeatWorldIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.physics_tick_heartbeat().world_id().find(...)`.
pub struct PhysicsTickHeartbeatWorldIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PhysicsTickHeartbeat, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PhysicsTickHeartbeatTableHandle<'ctx> {
    /// Get a handle on the `world_id` unique index on the table `physics_tick_heartbeat`.
    pub fn world_id(&self) -> PhysicsTickHeartbeatWorldIdUnique<'ctx> {
        PhysicsTickHeartbeatWorldIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("world_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PhysicsTickHeartbeatWorldIdUnique<'ctx> {
    /// Find the subscribed row whose `world_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PhysicsTickHeartbeat> {
        self.imp.find(col_val)
    }
}
