// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::secondary_type_type::SecondaryType;
use super::weapon_type_type::WeaponType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Player {
    pub identity: __sdk::Identity,
    pub name: String,
    pub lobby_id: u64,
    pub rigid_body_id: u64,
    pub position_x: f32,
    pub position_y: f32,
    pub position_z: f32,
    pub spawn_x: f32,
    pub spawn_y: f32,
    pub spawn_z: f32,
    pub health: i32,
    pub max_health: i32,
    pub is_alive: bool,
    pub team: i32,
    pub kills: i32,
    pub deaths: i32,
    pub weapon: WeaponType,
    pub secondary: SecondaryType,
    pub grenades: i32,
    pub molotovs: i32,
    pub color_r: f32,
    pub color_g: f32,
    pub color_b: f32,
    pub design_id: u8,
    pub secondary_color_r: f32,
    pub secondary_color_g: f32,
    pub secondary_color_b: f32,
    pub velocity_x: f32,
    pub velocity_y: f32,
    pub velocity_z: f32,
    pub input_x: f32,
    pub input_z: f32,
    pub aim_x: f32,
    pub aim_z: f32,
    pub is_shooting: bool,
    pub respawn_at: i64,
    pub last_shot_at: i64,
    pub joined_at: __sdk::Timestamp,
    pub last_impulse_x: f32,
    pub last_impulse_y: f32,
    pub last_impulse_z: f32,
    pub last_impulse_time: i64,
}

impl __sdk::InModule for Player {
    type Module = super::RemoteModule;
}
