// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Projectile {
    pub rigid_body_id: u64,
    pub owner_id: __sdk::Identity,
    pub damage: f32,
    pub radius: f32,
    pub can_detonate: bool,
}

impl __sdk::InModule for Projectile {
    type Module = super::RemoteModule;
}
