// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::physics_world_type::PhysicsWorld;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `rapier_physics_world`.
///
/// Obtain a handle from the [`RapierPhysicsWorldTableAccess::rapier_physics_world`] method on [`super::RemoteTables`],
/// like `ctx.db.rapier_physics_world()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rapier_physics_world().on_insert(...)`.
pub struct RapierPhysicsWorldTableHandle<'ctx> {
    imp: __sdk::TableHandle<PhysicsWorld>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `rapier_physics_world`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RapierPhysicsWorldTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RapierPhysicsWorldTableHandle`], which mediates access to the table `rapier_physics_world`.
    fn rapier_physics_world(&self) -> RapierPhysicsWorldTableHandle<'_>;
}

impl RapierPhysicsWorldTableAccess for super::RemoteTables {
    fn rapier_physics_world(&self) -> RapierPhysicsWorldTableHandle<'_> {
        RapierPhysicsWorldTableHandle {
            imp: self.imp.get_table::<PhysicsWorld>("rapier_physics_world"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RapierPhysicsWorldInsertCallbackId(__sdk::CallbackId);
pub struct RapierPhysicsWorldDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RapierPhysicsWorldTableHandle<'ctx> {
    type Row = PhysicsWorld;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PhysicsWorld> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RapierPhysicsWorldInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RapierPhysicsWorldInsertCallbackId {
        RapierPhysicsWorldInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RapierPhysicsWorldInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RapierPhysicsWorldDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RapierPhysicsWorldDeleteCallbackId {
        RapierPhysicsWorldDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RapierPhysicsWorldDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PhysicsWorld>("rapier_physics_world");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct RapierPhysicsWorldUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RapierPhysicsWorldTableHandle<'ctx> {
    type UpdateCallbackId = RapierPhysicsWorldUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RapierPhysicsWorldUpdateCallbackId {
        RapierPhysicsWorldUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RapierPhysicsWorldUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PhysicsWorld>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PhysicsWorld>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `rapier_physics_world`,
/// which allows point queries on the field of the same name
/// via the [`RapierPhysicsWorldIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rapier_physics_world().id().find(...)`.
pub struct RapierPhysicsWorldIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PhysicsWorld, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RapierPhysicsWorldTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `rapier_physics_world`.
    pub fn id(&self) -> RapierPhysicsWorldIdUnique<'ctx> {
        RapierPhysicsWorldIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RapierPhysicsWorldIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PhysicsWorld> {
        self.imp.find(col_val)
    }
}
