// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::rigid_body_type::RigidBody;
use super::rigid_body_type_type::RigidBodyType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `rapier_rigid_body`.
///
/// Obtain a handle from the [`RapierRigidBodyTableAccess::rapier_rigid_body`] method on [`super::RemoteTables`],
/// like `ctx.db.rapier_rigid_body()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rapier_rigid_body().on_insert(...)`.
pub struct RapierRigidBodyTableHandle<'ctx> {
    imp: __sdk::TableHandle<RigidBody>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `rapier_rigid_body`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RapierRigidBodyTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RapierRigidBodyTableHandle`], which mediates access to the table `rapier_rigid_body`.
    fn rapier_rigid_body(&self) -> RapierRigidBodyTableHandle<'_>;
}

impl RapierRigidBodyTableAccess for super::RemoteTables {
    fn rapier_rigid_body(&self) -> RapierRigidBodyTableHandle<'_> {
        RapierRigidBodyTableHandle {
            imp: self.imp.get_table::<RigidBody>("rapier_rigid_body"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RapierRigidBodyInsertCallbackId(__sdk::CallbackId);
pub struct RapierRigidBodyDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RapierRigidBodyTableHandle<'ctx> {
    type Row = RigidBody;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RigidBody> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RapierRigidBodyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RapierRigidBodyInsertCallbackId {
        RapierRigidBodyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RapierRigidBodyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RapierRigidBodyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RapierRigidBodyDeleteCallbackId {
        RapierRigidBodyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RapierRigidBodyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RigidBody>("rapier_rigid_body");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct RapierRigidBodyUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RapierRigidBodyTableHandle<'ctx> {
    type UpdateCallbackId = RapierRigidBodyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RapierRigidBodyUpdateCallbackId {
        RapierRigidBodyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RapierRigidBodyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<RigidBody>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RigidBody>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `rapier_rigid_body`,
/// which allows point queries on the field of the same name
/// via the [`RapierRigidBodyIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rapier_rigid_body().id().find(...)`.
pub struct RapierRigidBodyIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RigidBody, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RapierRigidBodyTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `rapier_rigid_body`.
    pub fn id(&self) -> RapierRigidBodyIdUnique<'ctx> {
        RapierRigidBodyIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RapierRigidBodyIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RigidBody> {
        self.imp.find(col_val)
    }
}
