// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sensor_collision_type::SensorCollision;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `rapier_sensor_collision`.
///
/// Obtain a handle from the [`RapierSensorCollisionTableAccess::rapier_sensor_collision`] method on [`super::RemoteTables`],
/// like `ctx.db.rapier_sensor_collision()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rapier_sensor_collision().on_insert(...)`.
pub struct RapierSensorCollisionTableHandle<'ctx> {
    imp: __sdk::TableHandle<SensorCollision>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `rapier_sensor_collision`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RapierSensorCollisionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RapierSensorCollisionTableHandle`], which mediates access to the table `rapier_sensor_collision`.
    fn rapier_sensor_collision(&self) -> RapierSensorCollisionTableHandle<'_>;
}

impl RapierSensorCollisionTableAccess for super::RemoteTables {
    fn rapier_sensor_collision(&self) -> RapierSensorCollisionTableHandle<'_> {
        RapierSensorCollisionTableHandle {
            imp: self
                .imp
                .get_table::<SensorCollision>("rapier_sensor_collision"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RapierSensorCollisionInsertCallbackId(__sdk::CallbackId);
pub struct RapierSensorCollisionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RapierSensorCollisionTableHandle<'ctx> {
    type Row = SensorCollision;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SensorCollision> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RapierSensorCollisionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RapierSensorCollisionInsertCallbackId {
        RapierSensorCollisionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RapierSensorCollisionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RapierSensorCollisionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RapierSensorCollisionDeleteCallbackId {
        RapierSensorCollisionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RapierSensorCollisionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SensorCollision>("rapier_sensor_collision");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct RapierSensorCollisionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RapierSensorCollisionTableHandle<'ctx> {
    type UpdateCallbackId = RapierSensorCollisionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RapierSensorCollisionUpdateCallbackId {
        RapierSensorCollisionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RapierSensorCollisionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SensorCollision>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SensorCollision>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `rapier_sensor_collision`,
/// which allows point queries on the field of the same name
/// via the [`RapierSensorCollisionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rapier_sensor_collision().id().find(...)`.
pub struct RapierSensorCollisionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SensorCollision, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RapierSensorCollisionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `rapier_sensor_collision`.
    pub fn id(&self) -> RapierSensorCollisionIdUnique<'ctx> {
        RapierSensorCollisionIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RapierSensorCollisionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SensorCollision> {
        self.imp.find(col_val)
    }
}
