// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::trigger_type::Trigger;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `rapier_trigger`.
///
/// Obtain a handle from the [`RapierTriggerTableAccess::rapier_trigger`] method on [`super::RemoteTables`],
/// like `ctx.db.rapier_trigger()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rapier_trigger().on_insert(...)`.
pub struct RapierTriggerTableHandle<'ctx> {
    imp: __sdk::TableHandle<Trigger>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `rapier_trigger`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RapierTriggerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RapierTriggerTableHandle`], which mediates access to the table `rapier_trigger`.
    fn rapier_trigger(&self) -> RapierTriggerTableHandle<'_>;
}

impl RapierTriggerTableAccess for super::RemoteTables {
    fn rapier_trigger(&self) -> RapierTriggerTableHandle<'_> {
        RapierTriggerTableHandle {
            imp: self.imp.get_table::<Trigger>("rapier_trigger"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RapierTriggerInsertCallbackId(__sdk::CallbackId);
pub struct RapierTriggerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RapierTriggerTableHandle<'ctx> {
    type Row = Trigger;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Trigger> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RapierTriggerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RapierTriggerInsertCallbackId {
        RapierTriggerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RapierTriggerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RapierTriggerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RapierTriggerDeleteCallbackId {
        RapierTriggerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RapierTriggerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Trigger>("rapier_trigger");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct RapierTriggerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RapierTriggerTableHandle<'ctx> {
    type UpdateCallbackId = RapierTriggerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RapierTriggerUpdateCallbackId {
        RapierTriggerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RapierTriggerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Trigger>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Trigger>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `rapier_trigger`,
/// which allows point queries on the field of the same name
/// via the [`RapierTriggerIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rapier_trigger().id().find(...)`.
pub struct RapierTriggerIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Trigger, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RapierTriggerTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `rapier_trigger`.
    pub fn id(&self) -> RapierTriggerIdUnique<'ctx> {
        RapierTriggerIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RapierTriggerIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Trigger> {
        self.imp.find(col_val)
    }
}
