// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ray_cast_hit_type::RayCastHit;
use super::ray_cast_type::RayCast;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `rapier_raycast`.
///
/// Obtain a handle from the [`RapierRaycastTableAccess::rapier_raycast`] method on [`super::RemoteTables`],
/// like `ctx.db.rapier_raycast()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rapier_raycast().on_insert(...)`.
pub struct RapierRaycastTableHandle<'ctx> {
    imp: __sdk::TableHandle<RayCast>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `rapier_raycast`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RapierRaycastTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RapierRaycastTableHandle`], which mediates access to the table `rapier_raycast`.
    fn rapier_raycast(&self) -> RapierRaycastTableHandle<'_>;
}

impl RapierRaycastTableAccess for super::RemoteTables {
    fn rapier_raycast(&self) -> RapierRaycastTableHandle<'_> {
        RapierRaycastTableHandle {
            imp: self.imp.get_table::<RayCast>("rapier_raycast"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RapierRaycastInsertCallbackId(__sdk::CallbackId);
pub struct RapierRaycastDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RapierRaycastTableHandle<'ctx> {
    type Row = RayCast;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RayCast> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RapierRaycastInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RapierRaycastInsertCallbackId {
        RapierRaycastInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RapierRaycastInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RapierRaycastDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RapierRaycastDeleteCallbackId {
        RapierRaycastDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RapierRaycastDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RayCast>("rapier_raycast");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct RapierRaycastUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RapierRaycastTableHandle<'ctx> {
    type UpdateCallbackId = RapierRaycastUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RapierRaycastUpdateCallbackId {
        RapierRaycastUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RapierRaycastUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<RayCast>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RayCast>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `rapier_raycast`,
/// which allows point queries on the field of the same name
/// via the [`RapierRaycastIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rapier_raycast().id().find(...)`.
pub struct RapierRaycastIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RayCast, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RapierRaycastTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `rapier_raycast`.
    pub fn id(&self) -> RapierRaycastIdUnique<'ctx> {
        RapierRaycastIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RapierRaycastIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RayCast> {
        self.imp.find(col_val)
    }
}
