// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::collider_type::Collider;
use super::collider_type_type::ColliderType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `rapier_collider`.
///
/// Obtain a handle from the [`RapierColliderTableAccess::rapier_collider`] method on [`super::RemoteTables`],
/// like `ctx.db.rapier_collider()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rapier_collider().on_insert(...)`.
pub struct RapierColliderTableHandle<'ctx> {
    imp: __sdk::TableHandle<Collider>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `rapier_collider`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RapierColliderTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RapierColliderTableHandle`], which mediates access to the table `rapier_collider`.
    fn rapier_collider(&self) -> RapierColliderTableHandle<'_>;
}

impl RapierColliderTableAccess for super::RemoteTables {
    fn rapier_collider(&self) -> RapierColliderTableHandle<'_> {
        RapierColliderTableHandle {
            imp: self.imp.get_table::<Collider>("rapier_collider"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RapierColliderInsertCallbackId(__sdk::CallbackId);
pub struct RapierColliderDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RapierColliderTableHandle<'ctx> {
    type Row = Collider;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Collider> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RapierColliderInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RapierColliderInsertCallbackId {
        RapierColliderInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RapierColliderInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RapierColliderDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RapierColliderDeleteCallbackId {
        RapierColliderDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RapierColliderDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Collider>("rapier_collider");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct RapierColliderUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RapierColliderTableHandle<'ctx> {
    type UpdateCallbackId = RapierColliderUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RapierColliderUpdateCallbackId {
        RapierColliderUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RapierColliderUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Collider>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Collider>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `rapier_collider`,
/// which allows point queries on the field of the same name
/// via the [`RapierColliderIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.rapier_collider().id().find(...)`.
pub struct RapierColliderIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Collider, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RapierColliderTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `rapier_collider`.
    pub fn id(&self) -> RapierColliderIdUnique<'ctx> {
        RapierColliderIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RapierColliderIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Collider> {
        self.imp.find(col_val)
    }
}
