// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::secondary_type_type::SecondaryType;
use super::weapon_type_type::WeaponType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestSpawnArgs {
    pub weapon: WeaponType,
    pub secondary: SecondaryType,
}

impl From<RequestSpawnArgs> for super::Reducer {
    fn from(args: RequestSpawnArgs) -> Self {
        Self::RequestSpawn {
            weapon: args.weapon,
            secondary: args.secondary,
        }
    }
}

impl __sdk::InModule for RequestSpawnArgs {
    type Module = super::RemoteModule;
}

pub struct RequestSpawnCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_spawn`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_spawn {
    /// Request that the remote module invoke the reducer `request_spawn` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_request_spawn`] callbacks.
    fn request_spawn(&self, weapon: WeaponType, secondary: SecondaryType) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `request_spawn`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RequestSpawnCallbackId`] can be passed to [`Self::remove_on_request_spawn`]
    /// to cancel the callback.
    fn on_request_spawn(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &WeaponType, &SecondaryType) + Send + 'static,
    ) -> RequestSpawnCallbackId;
    /// Cancel a callback previously registered by [`Self::on_request_spawn`],
    /// causing it not to run in the future.
    fn remove_on_request_spawn(&self, callback: RequestSpawnCallbackId);
}

impl request_spawn for super::RemoteReducers {
    fn request_spawn(&self, weapon: WeaponType, secondary: SecondaryType) -> __sdk::Result<()> {
        self.imp
            .call_reducer("request_spawn", RequestSpawnArgs { weapon, secondary })
    }
    fn on_request_spawn(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &WeaponType, &SecondaryType)
            + Send
            + 'static,
    ) -> RequestSpawnCallbackId {
        RequestSpawnCallbackId(self.imp.on_reducer(
            "request_spawn",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RequestSpawn { weapon, secondary },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, weapon, secondary)
            }),
        ))
    }
    fn remove_on_request_spawn(&self, callback: RequestSpawnCallbackId) {
        self.imp.remove_on_reducer("request_spawn", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `request_spawn`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_request_spawn {
    /// Set the call-reducer flags for the reducer `request_spawn` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn request_spawn(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_request_spawn for super::SetReducerFlags {
    fn request_spawn(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("request_spawn", flags);
    }
}
