// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetShootingArgs {
    pub is_shooting: bool,
    pub aim_x: f32,
    pub aim_z: f32,
}

impl From<SetShootingArgs> for super::Reducer {
    fn from(args: SetShootingArgs) -> Self {
        Self::SetShooting {
            is_shooting: args.is_shooting,
            aim_x: args.aim_x,
            aim_z: args.aim_z,
        }
    }
}

impl __sdk::InModule for SetShootingArgs {
    type Module = super::RemoteModule;
}

pub struct SetShootingCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_shooting`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_shooting {
    /// Request that the remote module invoke the reducer `set_shooting` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_shooting`] callbacks.
    fn set_shooting(&self, is_shooting: bool, aim_x: f32, aim_z: f32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_shooting`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetShootingCallbackId`] can be passed to [`Self::remove_on_set_shooting`]
    /// to cancel the callback.
    fn on_set_shooting(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &bool, &f32, &f32) + Send + 'static,
    ) -> SetShootingCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_shooting`],
    /// causing it not to run in the future.
    fn remove_on_set_shooting(&self, callback: SetShootingCallbackId);
}

impl set_shooting for super::RemoteReducers {
    fn set_shooting(&self, is_shooting: bool, aim_x: f32, aim_z: f32) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "set_shooting",
            SetShootingArgs {
                is_shooting,
                aim_x,
                aim_z,
            },
        )
    }
    fn on_set_shooting(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &bool, &f32, &f32) + Send + 'static,
    ) -> SetShootingCallbackId {
        SetShootingCallbackId(self.imp.on_reducer(
            "set_shooting",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::SetShooting {
                                    is_shooting,
                                    aim_x,
                                    aim_z,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, is_shooting, aim_x, aim_z)
            }),
        ))
    }
    fn remove_on_set_shooting(&self, callback: SetShootingCallbackId) {
        self.imp.remove_on_reducer("set_shooting", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `set_shooting`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_set_shooting {
    /// Set the call-reducer flags for the reducer `set_shooting` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn set_shooting(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_set_shooting for super::SetReducerFlags {
    fn set_shooting(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("set_shooting", flags);
    }
}
