// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetMarbleConfigArgs {
    pub design_id: u8,
    pub main_r: f32,
    pub main_g: f32,
    pub main_b: f32,
    pub sec_r: f32,
    pub sec_g: f32,
    pub sec_b: f32,
}

impl From<SetMarbleConfigArgs> for super::Reducer {
    fn from(args: SetMarbleConfigArgs) -> Self {
        Self::SetMarbleConfig {
            design_id: args.design_id,
            main_r: args.main_r,
            main_g: args.main_g,
            main_b: args.main_b,
            sec_r: args.sec_r,
            sec_g: args.sec_g,
            sec_b: args.sec_b,
        }
    }
}

impl __sdk::InModule for SetMarbleConfigArgs {
    type Module = super::RemoteModule;
}

pub struct SetMarbleConfigCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_marble_config`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_marble_config {
    /// Request that the remote module invoke the reducer `set_marble_config` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_marble_config`] callbacks.
    fn set_marble_config(
        &self,
        design_id: u8,
        main_r: f32,
        main_g: f32,
        main_b: f32,
        sec_r: f32,
        sec_g: f32,
        sec_b: f32,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_marble_config`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetMarbleConfigCallbackId`] can be passed to [`Self::remove_on_set_marble_config`]
    /// to cancel the callback.
    fn on_set_marble_config(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u8, &f32, &f32, &f32, &f32, &f32, &f32)
            + Send
            + 'static,
    ) -> SetMarbleConfigCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_marble_config`],
    /// causing it not to run in the future.
    fn remove_on_set_marble_config(&self, callback: SetMarbleConfigCallbackId);
}

impl set_marble_config for super::RemoteReducers {
    fn set_marble_config(
        &self,
        design_id: u8,
        main_r: f32,
        main_g: f32,
        main_b: f32,
        sec_r: f32,
        sec_g: f32,
        sec_b: f32,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "set_marble_config",
            SetMarbleConfigArgs {
                design_id,
                main_r,
                main_g,
                main_b,
                sec_r,
                sec_g,
                sec_b,
            },
        )
    }
    fn on_set_marble_config(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u8, &f32, &f32, &f32, &f32, &f32, &f32)
            + Send
            + 'static,
    ) -> SetMarbleConfigCallbackId {
        SetMarbleConfigCallbackId(self.imp.on_reducer(
            "set_marble_config",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::SetMarbleConfig {
                                    design_id,
                                    main_r,
                                    main_g,
                                    main_b,
                                    sec_r,
                                    sec_g,
                                    sec_b,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, design_id, main_r, main_g, main_b, sec_r, sec_g, sec_b)
            }),
        ))
    }
    fn remove_on_set_marble_config(&self, callback: SetMarbleConfigCallbackId) {
        self.imp.remove_on_reducer("set_marble_config", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `set_marble_config`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_set_marble_config {
    /// Set the call-reducer flags for the reducer `set_marble_config` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn set_marble_config(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_set_marble_config for super::SetReducerFlags {
    fn set_marble_config(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("set_marble_config", flags);
    }
}
