// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetPlayerColorArgs {
    pub r: f32,
    pub g: f32,
    pub b: f32,
}

impl From<SetPlayerColorArgs> for super::Reducer {
    fn from(args: SetPlayerColorArgs) -> Self {
        Self::SetPlayerColor {
            r: args.r,
            g: args.g,
            b: args.b,
        }
    }
}

impl __sdk::InModule for SetPlayerColorArgs {
    type Module = super::RemoteModule;
}

pub struct SetPlayerColorCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_player_color`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_player_color {
    /// Request that the remote module invoke the reducer `set_player_color` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_player_color`] callbacks.
    fn set_player_color(&self, r: f32, g: f32, b: f32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_player_color`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetPlayerColorCallbackId`] can be passed to [`Self::remove_on_set_player_color`]
    /// to cancel the callback.
    fn on_set_player_color(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &f32, &f32, &f32) + Send + 'static,
    ) -> SetPlayerColorCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_player_color`],
    /// causing it not to run in the future.
    fn remove_on_set_player_color(&self, callback: SetPlayerColorCallbackId);
}

impl set_player_color for super::RemoteReducers {
    fn set_player_color(&self, r: f32, g: f32, b: f32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("set_player_color", SetPlayerColorArgs { r, g, b })
    }
    fn on_set_player_color(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &f32, &f32, &f32) + Send + 'static,
    ) -> SetPlayerColorCallbackId {
        SetPlayerColorCallbackId(self.imp.on_reducer(
            "set_player_color",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SetPlayerColor { r, g, b },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, r, g, b)
            }),
        ))
    }
    fn remove_on_set_player_color(&self, callback: SetPlayerColorCallbackId) {
        self.imp.remove_on_reducer("set_player_color", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `set_player_color`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_set_player_color {
    /// Set the call-reducer flags for the reducer `set_player_color` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn set_player_color(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_set_player_color for super::SetReducerFlags {
    fn set_player_color(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("set_player_color", flags);
    }
}
