// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::secondary_type_type::SecondaryType;
use super::weapon_type_type::WeaponType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetLoadoutArgs {
    pub weapon: WeaponType,
    pub secondary: SecondaryType,
}

impl From<SetLoadoutArgs> for super::Reducer {
    fn from(args: SetLoadoutArgs) -> Self {
        Self::SetLoadout {
            weapon: args.weapon,
            secondary: args.secondary,
        }
    }
}

impl __sdk::InModule for SetLoadoutArgs {
    type Module = super::RemoteModule;
}

pub struct SetLoadoutCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_loadout`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_loadout {
    /// Request that the remote module invoke the reducer `set_loadout` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_loadout`] callbacks.
    fn set_loadout(&self, weapon: WeaponType, secondary: SecondaryType) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_loadout`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetLoadoutCallbackId`] can be passed to [`Self::remove_on_set_loadout`]
    /// to cancel the callback.
    fn on_set_loadout(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &WeaponType, &SecondaryType) + Send + 'static,
    ) -> SetLoadoutCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_loadout`],
    /// causing it not to run in the future.
    fn remove_on_set_loadout(&self, callback: SetLoadoutCallbackId);
}

impl set_loadout for super::RemoteReducers {
    fn set_loadout(&self, weapon: WeaponType, secondary: SecondaryType) -> __sdk::Result<()> {
        self.imp
            .call_reducer("set_loadout", SetLoadoutArgs { weapon, secondary })
    }
    fn on_set_loadout(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &WeaponType, &SecondaryType)
            + Send
            + 'static,
    ) -> SetLoadoutCallbackId {
        SetLoadoutCallbackId(self.imp.on_reducer(
            "set_loadout",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SetLoadout { weapon, secondary },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, weapon, secondary)
            }),
        ))
    }
    fn remove_on_set_loadout(&self, callback: SetLoadoutCallbackId) {
        self.imp.remove_on_reducer("set_loadout", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `set_loadout`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_set_loadout {
    /// Set the call-reducer flags for the reducer `set_loadout` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn set_loadout(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_set_loadout for super::SetReducerFlags {
    fn set_loadout(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("set_loadout", flags);
    }
}
