// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ShootArgs {}

impl From<ShootArgs> for super::Reducer {
    fn from(args: ShootArgs) -> Self {
        Self::Shoot
    }
}

impl __sdk::InModule for ShootArgs {
    type Module = super::RemoteModule;
}

pub struct ShootCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `shoot`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait shoot {
    /// Request that the remote module invoke the reducer `shoot` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_shoot`] callbacks.
    fn shoot(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `shoot`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ShootCallbackId`] can be passed to [`Self::remove_on_shoot`]
    /// to cancel the callback.
    fn on_shoot(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ShootCallbackId;
    /// Cancel a callback previously registered by [`Self::on_shoot`],
    /// causing it not to run in the future.
    fn remove_on_shoot(&self, callback: ShootCallbackId);
}

impl shoot for super::RemoteReducers {
    fn shoot(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("shoot", ShootArgs {})
    }
    fn on_shoot(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ShootCallbackId {
        ShootCallbackId(self.imp.on_reducer(
            "shoot",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::Shoot {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_shoot(&self, callback: ShootCallbackId) {
        self.imp.remove_on_reducer("shoot", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `shoot`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_shoot {
    /// Set the call-reducer flags for the reducer `shoot` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn shoot(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_shoot for super::SetReducerFlags {
    fn shoot(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("shoot", flags);
    }
}
