// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ThrowGrenadeArgs {
    pub aim_x: f32,
    pub aim_z: f32,
}

impl From<ThrowGrenadeArgs> for super::Reducer {
    fn from(args: ThrowGrenadeArgs) -> Self {
        Self::ThrowGrenade {
            aim_x: args.aim_x,
            aim_z: args.aim_z,
        }
    }
}

impl __sdk::InModule for ThrowGrenadeArgs {
    type Module = super::RemoteModule;
}

pub struct ThrowGrenadeCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `throw_grenade`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait throw_grenade {
    /// Request that the remote module invoke the reducer `throw_grenade` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_throw_grenade`] callbacks.
    fn throw_grenade(&self, aim_x: f32, aim_z: f32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `throw_grenade`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ThrowGrenadeCallbackId`] can be passed to [`Self::remove_on_throw_grenade`]
    /// to cancel the callback.
    fn on_throw_grenade(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &f32, &f32) + Send + 'static,
    ) -> ThrowGrenadeCallbackId;
    /// Cancel a callback previously registered by [`Self::on_throw_grenade`],
    /// causing it not to run in the future.
    fn remove_on_throw_grenade(&self, callback: ThrowGrenadeCallbackId);
}

impl throw_grenade for super::RemoteReducers {
    fn throw_grenade(&self, aim_x: f32, aim_z: f32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("throw_grenade", ThrowGrenadeArgs { aim_x, aim_z })
    }
    fn on_throw_grenade(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &f32, &f32) + Send + 'static,
    ) -> ThrowGrenadeCallbackId {
        ThrowGrenadeCallbackId(self.imp.on_reducer(
            "throw_grenade",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ThrowGrenade { aim_x, aim_z },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, aim_x, aim_z)
            }),
        ))
    }
    fn remove_on_throw_grenade(&self, callback: ThrowGrenadeCallbackId) {
        self.imp.remove_on_reducer("throw_grenade", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `throw_grenade`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_throw_grenade {
    /// Set the call-reducer flags for the reducer `throw_grenade` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn throw_grenade(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_throw_grenade for super::SetReducerFlags {
    fn throw_grenade(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("throw_grenade", flags);
    }
}
