// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ThrowMolotovArgs {
    pub aim_x: f32,
    pub aim_z: f32,
}

impl From<ThrowMolotovArgs> for super::Reducer {
    fn from(args: ThrowMolotovArgs) -> Self {
        Self::ThrowMolotov {
            aim_x: args.aim_x,
            aim_z: args.aim_z,
        }
    }
}

impl __sdk::InModule for ThrowMolotovArgs {
    type Module = super::RemoteModule;
}

pub struct ThrowMolotovCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `throw_molotov`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait throw_molotov {
    /// Request that the remote module invoke the reducer `throw_molotov` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_throw_molotov`] callbacks.
    fn throw_molotov(&self, aim_x: f32, aim_z: f32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `throw_molotov`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ThrowMolotovCallbackId`] can be passed to [`Self::remove_on_throw_molotov`]
    /// to cancel the callback.
    fn on_throw_molotov(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &f32, &f32) + Send + 'static,
    ) -> ThrowMolotovCallbackId;
    /// Cancel a callback previously registered by [`Self::on_throw_molotov`],
    /// causing it not to run in the future.
    fn remove_on_throw_molotov(&self, callback: ThrowMolotovCallbackId);
}

impl throw_molotov for super::RemoteReducers {
    fn throw_molotov(&self, aim_x: f32, aim_z: f32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("throw_molotov", ThrowMolotovArgs { aim_x, aim_z })
    }
    fn on_throw_molotov(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &f32, &f32) + Send + 'static,
    ) -> ThrowMolotovCallbackId {
        ThrowMolotovCallbackId(self.imp.on_reducer(
            "throw_molotov",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ThrowMolotov { aim_x, aim_z },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, aim_x, aim_z)
            }),
        ))
    }
    fn remove_on_throw_molotov(&self, callback: ThrowMolotovCallbackId) {
        self.imp.remove_on_reducer("throw_molotov", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `throw_molotov`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_throw_molotov {
    /// Set the call-reducer flags for the reducer `throw_molotov` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn throw_molotov(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_throw_molotov for super::SetReducerFlags {
    fn throw_molotov(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("throw_molotov", flags);
    }
}
