// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Trigger {
    pub id: u64,
    pub world_id: u64,
    pub position_x: f32,
    pub position_y: f32,
    pub position_z: f32,
    pub rotation_x: f32,
    pub rotation_y: f32,
    pub rotation_z: f32,
    pub rotation_w: f32,
    pub collider_id: u64,
    pub entities_inside: Vec<u64>,
    pub added_entities: Vec<u64>,
    pub removed_entities: Vec<u64>,
    pub enabled: bool,
}

impl __sdk::InModule for Trigger {
    type Module = super::RemoteModule;
}
