// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateInputArgs {
    pub input_x: f32,
    pub input_z: f32,
    pub aim_x: f32,
    pub aim_z: f32,
    pub is_shooting: bool,
}

impl From<UpdateInputArgs> for super::Reducer {
    fn from(args: UpdateInputArgs) -> Self {
        Self::UpdateInput {
            input_x: args.input_x,
            input_z: args.input_z,
            aim_x: args.aim_x,
            aim_z: args.aim_z,
            is_shooting: args.is_shooting,
        }
    }
}

impl __sdk::InModule for UpdateInputArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateInputCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_input`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_input {
    /// Request that the remote module invoke the reducer `update_input` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_input`] callbacks.
    fn update_input(
        &self,
        input_x: f32,
        input_z: f32,
        aim_x: f32,
        aim_z: f32,
        is_shooting: bool,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_input`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateInputCallbackId`] can be passed to [`Self::remove_on_update_input`]
    /// to cancel the callback.
    fn on_update_input(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &f32, &f32, &f32, &f32, &bool)
            + Send
            + 'static,
    ) -> UpdateInputCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_input`],
    /// causing it not to run in the future.
    fn remove_on_update_input(&self, callback: UpdateInputCallbackId);
}

impl update_input for super::RemoteReducers {
    fn update_input(
        &self,
        input_x: f32,
        input_z: f32,
        aim_x: f32,
        aim_z: f32,
        is_shooting: bool,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "update_input",
            UpdateInputArgs {
                input_x,
                input_z,
                aim_x,
                aim_z,
                is_shooting,
            },
        )
    }
    fn on_update_input(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &f32, &f32, &f32, &f32, &bool)
            + Send
            + 'static,
    ) -> UpdateInputCallbackId {
        UpdateInputCallbackId(self.imp.on_reducer(
            "update_input",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::UpdateInput {
                                    input_x,
                                    input_z,
                                    aim_x,
                                    aim_z,
                                    is_shooting,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, input_x, input_z, aim_x, aim_z, is_shooting)
            }),
        ))
    }
    fn remove_on_update_input(&self, callback: UpdateInputCallbackId) {
        self.imp.remove_on_reducer("update_input", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_input`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_input {
    /// Set the call-reducer flags for the reducer `update_input` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_input(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_input for super::SetReducerFlags {
    fn update_input(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("update_input", flags);
    }
}
