// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UseSecondaryArgs {}

impl From<UseSecondaryArgs> for super::Reducer {
    fn from(args: UseSecondaryArgs) -> Self {
        Self::UseSecondary
    }
}

impl __sdk::InModule for UseSecondaryArgs {
    type Module = super::RemoteModule;
}

pub struct UseSecondaryCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `use_secondary`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait use_secondary {
    /// Request that the remote module invoke the reducer `use_secondary` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_use_secondary`] callbacks.
    fn use_secondary(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `use_secondary`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UseSecondaryCallbackId`] can be passed to [`Self::remove_on_use_secondary`]
    /// to cancel the callback.
    fn on_use_secondary(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> UseSecondaryCallbackId;
    /// Cancel a callback previously registered by [`Self::on_use_secondary`],
    /// causing it not to run in the future.
    fn remove_on_use_secondary(&self, callback: UseSecondaryCallbackId);
}

impl use_secondary for super::RemoteReducers {
    fn use_secondary(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("use_secondary", UseSecondaryArgs {})
    }
    fn on_use_secondary(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> UseSecondaryCallbackId {
        UseSecondaryCallbackId(self.imp.on_reducer(
            "use_secondary",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UseSecondary {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_use_secondary(&self, callback: UseSecondaryCallbackId) {
        self.imp.remove_on_reducer("use_secondary", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `use_secondary`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_use_secondary {
    /// Set the call-reducer flags for the reducer `use_secondary` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn use_secondary(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_use_secondary for super::SetReducerFlags {
    fn use_secondary(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("use_secondary", flags);
    }
}
