// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file actions.proto (package gyrii, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { GameMode, MapId, SecondaryType, WeaponType } from "./common_pb";
import { file_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file actions.proto.
 */
export const file_actions: GenFile = /*@__PURE__*/
  fileDesc("Cg1hY3Rpb25zLnByb3RvEgVneXJpaSIkCgxBdXRoZW50aWNhdGUSFAoMYWNjZXNzX3Rva2VuGAEgASgJIg0KC0xpc3RMb2JiaWVzIq0CCgtDcmVhdGVMb2JieRIMCgRuYW1lGAEgASgJEhgKEGhvc3RfcGxheWVyX25hbWUYAiABKAkSHAoGbWFwX2lkGAMgASgOMgwuZ3lyaWkuTWFwSWQSHgoIbWFwX3Bvb2wYBCADKA4yDC5neXJpaS5NYXBJZBIiCglnYW1lX21vZGUYBSABKA4yDy5neXJpaS5HYW1lTW9kZRITCgttYXhfcGxheWVycxgGIAEoDRITCgtzY29yZV9saW1pdBgHIAEoBRISCgpmbGFnX2xpbWl0GAggASgFEhAKCHBhc3N3b3JkGAkgASgJEhwKD2N1c3RvbV9tYXBfanNvbhgKIAEoCUgAiAEBEhIKCnRlYW1fY291bnQYCyABKAVCEgoQX2N1c3RvbV9tYXBfanNvbiJECglKb2luTG9iYnkSEAoIbG9iYnlfaWQYASABKAQSEwoLcGxheWVyX25hbWUYAiABKAkSEAoIcGFzc3dvcmQYAyABKAkiEwoRUmVxdWVzdExvYmJ5U3RhdGUiDAoKTGVhdmVMb2JieSIZCghTZXRSZWFkeRINCgVyZWFkeRgBIAEoCCILCglTdGFydEdhbWUiGwoHRW5kR2FtZRIQCghsb2JieV9pZBgBIAEoBCJaCgxSZXF1ZXN0U3Bhd24SIQoGd2VhcG9uGAEgASgOMhEuZ3lyaWkuV2VhcG9uVHlwZRInCglzZWNvbmRhcnkYAiABKA4yFC5neXJpaS5TZWNvbmRhcnlUeXBlIk0KC1VwZGF0ZUlucHV0Eg8KB2lucHV0X3gYASABKAISDwoHaW5wdXRfehgCIAEoAhINCgVhaW1feBgDIAEoAhINCgVhaW1fehgEIAEoAiJACgtTZXRTaG9vdGluZxITCgtpc19zaG9vdGluZxgBIAEoCBINCgVhaW1feBgCIAEoAhINCgVhaW1fehgDIAEoAiJYCgpTZXRMb2Fkb3V0EiEKBndlYXBvbhgBIAEoDjIRLmd5cmlpLldlYXBvblR5cGUSJwoJc2Vjb25kYXJ5GAIgASgOMhQuZ3lyaWkuU2Vjb25kYXJ5VHlwZSKBAQoPU2V0TWFyYmxlQ29uZmlnEhEKCWRlc2lnbl9pZBgBIAEoDRIOCgZtYWluX3IYAiABKAISDgoGbWFpbl9nGAMgASgCEg4KBm1haW5fYhgEIAEoAhINCgVzZWNfchgFIAEoAhINCgVzZWNfZxgGIAEoAhINCgVzZWNfYhgHIAEoAiIHCgVTaG9vdCIQCg5EZXRvbmF0ZVJvY2tldCIsCgxUaHJvd0dyZW5hZGUSDQoFYWltX3gYASABKAISDQoFYWltX3oYAiABKAIiLAoMVGhyb3dNb2xvdG92Eg0KBWFpbV94GAEgASgCEg0KBWFpbV96GAIgASgCIg4KDFVzZVNlY29uZGFyeWIGcHJvdG8z", [file_common]);

/**
 * @generated from message gyrii.Authenticate
 */
export type Authenticate = Message<"gyrii.Authenticate"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;
};

/**
 * Describes the message gyrii.Authenticate.
 * Use `create(AuthenticateSchema)` to create a new message.
 */
export const AuthenticateSchema: GenMessage<Authenticate> = /*@__PURE__*/
  messageDesc(file_actions, 0);

/**
 * @generated from message gyrii.ListLobbies
 */
export type ListLobbies = Message<"gyrii.ListLobbies"> & {
};

/**
 * Describes the message gyrii.ListLobbies.
 * Use `create(ListLobbiesSchema)` to create a new message.
 */
export const ListLobbiesSchema: GenMessage<ListLobbies> = /*@__PURE__*/
  messageDesc(file_actions, 1);

/**
 * @generated from message gyrii.CreateLobby
 */
export type CreateLobby = Message<"gyrii.CreateLobby"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string host_player_name = 2;
   */
  hostPlayerName: string;

  /**
   * @generated from field: gyrii.MapId map_id = 3;
   */
  mapId: MapId;

  /**
   * @generated from field: repeated gyrii.MapId map_pool = 4;
   */
  mapPool: MapId[];

  /**
   * @generated from field: gyrii.GameMode game_mode = 5;
   */
  gameMode: GameMode;

  /**
   * @generated from field: uint32 max_players = 6;
   */
  maxPlayers: number;

  /**
   * @generated from field: int32 score_limit = 7;
   */
  scoreLimit: number;

  /**
   * @generated from field: int32 flag_limit = 8;
   */
  flagLimit: number;

  /**
   * @generated from field: string password = 9;
   */
  password: string;

  /**
   * @generated from field: optional string custom_map_json = 10;
   */
  customMapJson?: string;

  /**
   * 2-4 for team modes; default 2
   *
   * @generated from field: int32 team_count = 11;
   */
  teamCount: number;
};

/**
 * Describes the message gyrii.CreateLobby.
 * Use `create(CreateLobbySchema)` to create a new message.
 */
export const CreateLobbySchema: GenMessage<CreateLobby> = /*@__PURE__*/
  messageDesc(file_actions, 2);

/**
 * @generated from message gyrii.JoinLobby
 */
export type JoinLobby = Message<"gyrii.JoinLobby"> & {
  /**
   * @generated from field: uint64 lobby_id = 1;
   */
  lobbyId: bigint;

  /**
   * @generated from field: string player_name = 2;
   */
  playerName: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;
};

/**
 * Describes the message gyrii.JoinLobby.
 * Use `create(JoinLobbySchema)` to create a new message.
 */
export const JoinLobbySchema: GenMessage<JoinLobby> = /*@__PURE__*/
  messageDesc(file_actions, 3);

/**
 * @generated from message gyrii.RequestLobbyState
 */
export type RequestLobbyState = Message<"gyrii.RequestLobbyState"> & {
};

/**
 * Describes the message gyrii.RequestLobbyState.
 * Use `create(RequestLobbyStateSchema)` to create a new message.
 */
export const RequestLobbyStateSchema: GenMessage<RequestLobbyState> = /*@__PURE__*/
  messageDesc(file_actions, 4);

/**
 * @generated from message gyrii.LeaveLobby
 */
export type LeaveLobby = Message<"gyrii.LeaveLobby"> & {
};

/**
 * Describes the message gyrii.LeaveLobby.
 * Use `create(LeaveLobbySchema)` to create a new message.
 */
export const LeaveLobbySchema: GenMessage<LeaveLobby> = /*@__PURE__*/
  messageDesc(file_actions, 5);

/**
 * @generated from message gyrii.SetReady
 */
export type SetReady = Message<"gyrii.SetReady"> & {
  /**
   * @generated from field: bool ready = 1;
   */
  ready: boolean;
};

/**
 * Describes the message gyrii.SetReady.
 * Use `create(SetReadySchema)` to create a new message.
 */
export const SetReadySchema: GenMessage<SetReady> = /*@__PURE__*/
  messageDesc(file_actions, 6);

/**
 * @generated from message gyrii.StartGame
 */
export type StartGame = Message<"gyrii.StartGame"> & {
};

/**
 * Describes the message gyrii.StartGame.
 * Use `create(StartGameSchema)` to create a new message.
 */
export const StartGameSchema: GenMessage<StartGame> = /*@__PURE__*/
  messageDesc(file_actions, 7);

/**
 * @generated from message gyrii.EndGame
 */
export type EndGame = Message<"gyrii.EndGame"> & {
  /**
   * @generated from field: uint64 lobby_id = 1;
   */
  lobbyId: bigint;
};

/**
 * Describes the message gyrii.EndGame.
 * Use `create(EndGameSchema)` to create a new message.
 */
export const EndGameSchema: GenMessage<EndGame> = /*@__PURE__*/
  messageDesc(file_actions, 8);

/**
 * @generated from message gyrii.RequestSpawn
 */
export type RequestSpawn = Message<"gyrii.RequestSpawn"> & {
  /**
   * @generated from field: gyrii.WeaponType weapon = 1;
   */
  weapon: WeaponType;

  /**
   * @generated from field: gyrii.SecondaryType secondary = 2;
   */
  secondary: SecondaryType;
};

/**
 * Describes the message gyrii.RequestSpawn.
 * Use `create(RequestSpawnSchema)` to create a new message.
 */
export const RequestSpawnSchema: GenMessage<RequestSpawn> = /*@__PURE__*/
  messageDesc(file_actions, 9);

/**
 * @generated from message gyrii.UpdateInput
 */
export type UpdateInput = Message<"gyrii.UpdateInput"> & {
  /**
   * @generated from field: float input_x = 1;
   */
  inputX: number;

  /**
   * @generated from field: float input_z = 2;
   */
  inputZ: number;

  /**
   * @generated from field: float aim_x = 3;
   */
  aimX: number;

  /**
   * @generated from field: float aim_z = 4;
   */
  aimZ: number;
};

/**
 * Describes the message gyrii.UpdateInput.
 * Use `create(UpdateInputSchema)` to create a new message.
 */
export const UpdateInputSchema: GenMessage<UpdateInput> = /*@__PURE__*/
  messageDesc(file_actions, 10);

/**
 * @generated from message gyrii.SetShooting
 */
export type SetShooting = Message<"gyrii.SetShooting"> & {
  /**
   * @generated from field: bool is_shooting = 1;
   */
  isShooting: boolean;

  /**
   * @generated from field: float aim_x = 2;
   */
  aimX: number;

  /**
   * @generated from field: float aim_z = 3;
   */
  aimZ: number;
};

/**
 * Describes the message gyrii.SetShooting.
 * Use `create(SetShootingSchema)` to create a new message.
 */
export const SetShootingSchema: GenMessage<SetShooting> = /*@__PURE__*/
  messageDesc(file_actions, 11);

/**
 * @generated from message gyrii.SetLoadout
 */
export type SetLoadout = Message<"gyrii.SetLoadout"> & {
  /**
   * @generated from field: gyrii.WeaponType weapon = 1;
   */
  weapon: WeaponType;

  /**
   * @generated from field: gyrii.SecondaryType secondary = 2;
   */
  secondary: SecondaryType;
};

/**
 * Describes the message gyrii.SetLoadout.
 * Use `create(SetLoadoutSchema)` to create a new message.
 */
export const SetLoadoutSchema: GenMessage<SetLoadout> = /*@__PURE__*/
  messageDesc(file_actions, 12);

/**
 * @generated from message gyrii.SetMarbleConfig
 */
export type SetMarbleConfig = Message<"gyrii.SetMarbleConfig"> & {
  /**
   * @generated from field: uint32 design_id = 1;
   */
  designId: number;

  /**
   * @generated from field: float main_r = 2;
   */
  mainR: number;

  /**
   * @generated from field: float main_g = 3;
   */
  mainG: number;

  /**
   * @generated from field: float main_b = 4;
   */
  mainB: number;

  /**
   * @generated from field: float sec_r = 5;
   */
  secR: number;

  /**
   * @generated from field: float sec_g = 6;
   */
  secG: number;

  /**
   * @generated from field: float sec_b = 7;
   */
  secB: number;
};

/**
 * Describes the message gyrii.SetMarbleConfig.
 * Use `create(SetMarbleConfigSchema)` to create a new message.
 */
export const SetMarbleConfigSchema: GenMessage<SetMarbleConfig> = /*@__PURE__*/
  messageDesc(file_actions, 13);

/**
 * @generated from message gyrii.Shoot
 */
export type Shoot = Message<"gyrii.Shoot"> & {
};

/**
 * Describes the message gyrii.Shoot.
 * Use `create(ShootSchema)` to create a new message.
 */
export const ShootSchema: GenMessage<Shoot> = /*@__PURE__*/
  messageDesc(file_actions, 14);

/**
 * @generated from message gyrii.DetonateRocket
 */
export type DetonateRocket = Message<"gyrii.DetonateRocket"> & {
};

/**
 * Describes the message gyrii.DetonateRocket.
 * Use `create(DetonateRocketSchema)` to create a new message.
 */
export const DetonateRocketSchema: GenMessage<DetonateRocket> = /*@__PURE__*/
  messageDesc(file_actions, 15);

/**
 * @generated from message gyrii.ThrowGrenade
 */
export type ThrowGrenade = Message<"gyrii.ThrowGrenade"> & {
  /**
   * @generated from field: float aim_x = 1;
   */
  aimX: number;

  /**
   * @generated from field: float aim_z = 2;
   */
  aimZ: number;
};

/**
 * Describes the message gyrii.ThrowGrenade.
 * Use `create(ThrowGrenadeSchema)` to create a new message.
 */
export const ThrowGrenadeSchema: GenMessage<ThrowGrenade> = /*@__PURE__*/
  messageDesc(file_actions, 16);

/**
 * @generated from message gyrii.ThrowMolotov
 */
export type ThrowMolotov = Message<"gyrii.ThrowMolotov"> & {
  /**
   * @generated from field: float aim_x = 1;
   */
  aimX: number;

  /**
   * @generated from field: float aim_z = 2;
   */
  aimZ: number;
};

/**
 * Describes the message gyrii.ThrowMolotov.
 * Use `create(ThrowMolotovSchema)` to create a new message.
 */
export const ThrowMolotovSchema: GenMessage<ThrowMolotov> = /*@__PURE__*/
  messageDesc(file_actions, 17);

/**
 * @generated from message gyrii.UseSecondary
 */
export type UseSecondary = Message<"gyrii.UseSecondary"> & {
};

/**
 * Describes the message gyrii.UseSecondary.
 * Use `create(UseSecondarySchema)` to create a new message.
 */
export const UseSecondarySchema: GenMessage<UseSecondary> = /*@__PURE__*/
  messageDesc(file_actions, 18);

