// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file combat.proto (package gyrii, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { SecondaryType, WeaponType } from "./common_pb";
import { file_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file combat.proto.
 */
export const file_combat: GenFile = /*@__PURE__*/
  fileDesc("Cgxjb21iYXQucHJvdG8SBWd5cmlpItIBCglTaG90RXZlbnQSEQoJcGxheWVyX2lkGAEgASgMEiEKBndlYXBvbhgCIAEoDjIRLmd5cmlpLldlYXBvblR5cGUSFwoPcHJvamVjdGlsZV90eXBlGAMgASgNEhIKCnBvc2l0aW9uX3gYBCABKAISEgoKcG9zaXRpb25feRgFIAEoAhISCgpwb3NpdGlvbl96GAYgASgCEhIKCnZlbG9jaXR5X3gYByABKAISEgoKdmVsb2NpdHlfeRgIIAEoAhISCgp2ZWxvY2l0eV96GAkgASgCIvUBCg1HcmVuYWRlSW5zZXJ0EhUKDXJpZ2lkX2JvZHlfaWQYASABKAQSEgoKcG9zaXRpb25feBgCIAEoAhISCgpwb3NpdGlvbl95GAMgASgCEhIKCnBvc2l0aW9uX3oYBCABKAISEgoKdmVsb2NpdHlfeBgFIAEoAhISCgp2ZWxvY2l0eV95GAYgASgCEhIKCnZlbG9jaXR5X3oYByABKAISEAoIb3duZXJfaWQYCCABKAwSFQoNb3duZXJfY29sb3JfchgJIAEoAhIVCg1vd25lcl9jb2xvcl9nGAogASgCEhUKDW93bmVyX2NvbG9yX2IYCyABKAIiJgoNR3JlbmFkZURlbGV0ZRIVCg1yaWdpZF9ib2R5X2lkGAEgASgEIp4BCg1HcmVuYWRlVXBkYXRlEhUKDXJpZ2lkX2JvZHlfaWQYASABKAQSEgoKcG9zaXRpb25feBgCIAEoAhISCgpwb3NpdGlvbl95GAMgASgCEhIKCnBvc2l0aW9uX3oYBCABKAISEgoKdmVsb2NpdHlfeBgFIAEoAhISCgp2ZWxvY2l0eV95GAYgASgCEhIKCnZlbG9jaXR5X3oYByABKAIifgoJS2lsbEV2ZW50EhEKCWtpbGxlcl9pZBgBIAEoDBITCgtraWxsZXJfbmFtZRgCIAEoCRIRCgl2aWN0aW1faWQYAyABKAwSEwoLdmljdGltX25hbWUYBCABKAkSDgoGd2VhcG9uGAUgASgJEhEKCXRpbWVzdGFtcBgGIAEoBCKmAQoKUGhvdG9uQmVhbRIKCgJpZBgBIAEoBBIQCghvd25lcl9pZBgCIAEoDBIQCghvcmlnaW5feBgDIAEoAhIQCghvcmlnaW5feRgEIAEoAhIQCghvcmlnaW5fehgFIAEoAhINCgVlbmRfeBgGIAEoAhINCgVlbmRfeRgHIAEoAhINCgVlbmRfehgIIAEoAhIXCg9yZW1haW5pbmdfdGlja3MYCSABKAUivQEKFFNlY29uZGFyeUVmZmVjdEV2ZW50EhEKCXBsYXllcl9pZBgBIAEoDBIsCg5zZWNvbmRhcnlfdHlwZRgCIAEoDjIULmd5cmlpLlNlY29uZGFyeVR5cGUSEgoKcG9zaXRpb25feBgDIAEoAhISCgpwb3NpdGlvbl95GAQgASgCEhIKCnBvc2l0aW9uX3oYBSABKAISEwoLZGlyZWN0aW9uX3gYBiABKAISEwoLZGlyZWN0aW9uX3oYByABKAJiBnByb3RvMw", [file_common]);

/**
 * Shot event
 *
 * @generated from message gyrii.ShotEvent
 */
export type ShotEvent = Message<"gyrii.ShotEvent"> & {
  /**
   * @generated from field: bytes player_id = 1;
   */
  playerId: Uint8Array;

  /**
   * @generated from field: gyrii.WeaponType weapon = 2;
   */
  weapon: WeaponType;

  /**
   * @generated from field: uint32 projectile_type = 3;
   */
  projectileType: number;

  /**
   * @generated from field: float position_x = 4;
   */
  positionX: number;

  /**
   * @generated from field: float position_y = 5;
   */
  positionY: number;

  /**
   * @generated from field: float position_z = 6;
   */
  positionZ: number;

  /**
   * @generated from field: float velocity_x = 7;
   */
  velocityX: number;

  /**
   * @generated from field: float velocity_y = 8;
   */
  velocityY: number;

  /**
   * @generated from field: float velocity_z = 9;
   */
  velocityZ: number;
};

/**
 * Describes the message gyrii.ShotEvent.
 * Use `create(ShotEventSchema)` to create a new message.
 */
export const ShotEventSchema: GenMessage<ShotEvent> = /*@__PURE__*/
  messageDesc(file_combat, 0);

/**
 * Grenade insert
 *
 * @generated from message gyrii.GrenadeInsert
 */
export type GrenadeInsert = Message<"gyrii.GrenadeInsert"> & {
  /**
   * @generated from field: uint64 rigid_body_id = 1;
   */
  rigidBodyId: bigint;

  /**
   * @generated from field: float position_x = 2;
   */
  positionX: number;

  /**
   * @generated from field: float position_y = 3;
   */
  positionY: number;

  /**
   * @generated from field: float position_z = 4;
   */
  positionZ: number;

  /**
   * @generated from field: float velocity_x = 5;
   */
  velocityX: number;

  /**
   * @generated from field: float velocity_y = 6;
   */
  velocityY: number;

  /**
   * @generated from field: float velocity_z = 7;
   */
  velocityZ: number;

  /**
   * @generated from field: bytes owner_id = 8;
   */
  ownerId: Uint8Array;

  /**
   * @generated from field: float owner_color_r = 9;
   */
  ownerColorR: number;

  /**
   * @generated from field: float owner_color_g = 10;
   */
  ownerColorG: number;

  /**
   * @generated from field: float owner_color_b = 11;
   */
  ownerColorB: number;
};

/**
 * Describes the message gyrii.GrenadeInsert.
 * Use `create(GrenadeInsertSchema)` to create a new message.
 */
export const GrenadeInsertSchema: GenMessage<GrenadeInsert> = /*@__PURE__*/
  messageDesc(file_combat, 1);

/**
 * Grenade delete
 *
 * @generated from message gyrii.GrenadeDelete
 */
export type GrenadeDelete = Message<"gyrii.GrenadeDelete"> & {
  /**
   * @generated from field: uint64 rigid_body_id = 1;
   */
  rigidBodyId: bigint;
};

/**
 * Describes the message gyrii.GrenadeDelete.
 * Use `create(GrenadeDeleteSchema)` to create a new message.
 */
export const GrenadeDeleteSchema: GenMessage<GrenadeDelete> = /*@__PURE__*/
  messageDesc(file_combat, 2);

/**
 * Grenade update
 *
 * @generated from message gyrii.GrenadeUpdate
 */
export type GrenadeUpdate = Message<"gyrii.GrenadeUpdate"> & {
  /**
   * @generated from field: uint64 rigid_body_id = 1;
   */
  rigidBodyId: bigint;

  /**
   * @generated from field: float position_x = 2;
   */
  positionX: number;

  /**
   * @generated from field: float position_y = 3;
   */
  positionY: number;

  /**
   * @generated from field: float position_z = 4;
   */
  positionZ: number;

  /**
   * @generated from field: float velocity_x = 5;
   */
  velocityX: number;

  /**
   * @generated from field: float velocity_y = 6;
   */
  velocityY: number;

  /**
   * @generated from field: float velocity_z = 7;
   */
  velocityZ: number;
};

/**
 * Describes the message gyrii.GrenadeUpdate.
 * Use `create(GrenadeUpdateSchema)` to create a new message.
 */
export const GrenadeUpdateSchema: GenMessage<GrenadeUpdate> = /*@__PURE__*/
  messageDesc(file_combat, 3);

/**
 * Kill event (weapon is damage source: "bullet", "photon", "grenade", etc.)
 *
 * @generated from message gyrii.KillEvent
 */
export type KillEvent = Message<"gyrii.KillEvent"> & {
  /**
   * @generated from field: bytes killer_id = 1;
   */
  killerId: Uint8Array;

  /**
   * @generated from field: string killer_name = 2;
   */
  killerName: string;

  /**
   * @generated from field: bytes victim_id = 3;
   */
  victimId: Uint8Array;

  /**
   * @generated from field: string victim_name = 4;
   */
  victimName: string;

  /**
   * @generated from field: string weapon = 5;
   */
  weapon: string;

  /**
   * @generated from field: uint64 timestamp = 6;
   */
  timestamp: bigint;
};

/**
 * Describes the message gyrii.KillEvent.
 * Use `create(KillEventSchema)` to create a new message.
 */
export const KillEventSchema: GenMessage<KillEvent> = /*@__PURE__*/
  messageDesc(file_combat, 4);

/**
 * Photon beam
 *
 * @generated from message gyrii.PhotonBeam
 */
export type PhotonBeam = Message<"gyrii.PhotonBeam"> & {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: bytes owner_id = 2;
   */
  ownerId: Uint8Array;

  /**
   * @generated from field: float origin_x = 3;
   */
  originX: number;

  /**
   * @generated from field: float origin_y = 4;
   */
  originY: number;

  /**
   * @generated from field: float origin_z = 5;
   */
  originZ: number;

  /**
   * @generated from field: float end_x = 6;
   */
  endX: number;

  /**
   * @generated from field: float end_y = 7;
   */
  endY: number;

  /**
   * @generated from field: float end_z = 8;
   */
  endZ: number;

  /**
   * @generated from field: int32 remaining_ticks = 9;
   */
  remainingTicks: number;
};

/**
 * Describes the message gyrii.PhotonBeam.
 * Use `create(PhotonBeamSchema)` to create a new message.
 */
export const PhotonBeamSchema: GenMessage<PhotonBeam> = /*@__PURE__*/
  messageDesc(file_combat, 5);

/**
 * Secondary ability effect (hammers pop, dash poof) - broadcast for all players to render
 *
 * @generated from message gyrii.SecondaryEffectEvent
 */
export type SecondaryEffectEvent = Message<"gyrii.SecondaryEffectEvent"> & {
  /**
   * @generated from field: bytes player_id = 1;
   */
  playerId: Uint8Array;

  /**
   * @generated from field: gyrii.SecondaryType secondary_type = 2;
   */
  secondaryType: SecondaryType;

  /**
   * @generated from field: float position_x = 3;
   */
  positionX: number;

  /**
   * @generated from field: float position_y = 4;
   */
  positionY: number;

  /**
   * @generated from field: float position_z = 5;
   */
  positionZ: number;

  /**
   * @generated from field: float direction_x = 6;
   */
  directionX: number;

  /**
   * @generated from field: float direction_z = 7;
   */
  directionZ: number;
};

/**
 * Describes the message gyrii.SecondaryEffectEvent.
 * Use `create(SecondaryEffectEventSchema)` to create a new message.
 */
export const SecondaryEffectEventSchema: GenMessage<SecondaryEffectEvent> = /*@__PURE__*/
  messageDesc(file_combat, 6);

