// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file common.proto (package gyrii, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file common.proto.
 */
export const file_common: GenFile = /*@__PURE__*/
  fileDesc("Cgxjb21tb24ucHJvdG8SBWd5cmlpKsEBCgpXZWFwb25UeXBlEhYKEldFQVBPTl9VTlNQRUNJRklFRBAAEg4KCldFQVBPTl9TTUcQARIbChdXRUFQT05fRFVBTF9NQUNISU5FX0dVThACEhQKEFdFQVBPTl9DSEFJTl9HVU4QAxIXChNXRUFQT05fUEhPVE9OX1JJRkxFEAQSEgoOV0VBUE9OX0JBWk9PS0EQBRIXChNXRUFQT05fRkxBTUVUSFJPV0VSEAYSEgoOV0VBUE9OX1NIT1RHVU4QByq2AQoNU2Vjb25kYXJ5VHlwZRIZChVTRUNPTkRBUllfVU5TUEVDSUZJRUQQABIaChZTRUNPTkRBUllfUE9QVVBfS05JVkVTEAESGwoXU0VDT05EQVJZX0JVQkJMRV9TSElFTEQQAhIgChxTRUNPTkRBUllfU0VMRl9ERVNUUlVDVF9OVUtFEAMSGwoXU0VDT05EQVJZX1BPUFVQX0hBTU1FUlMQBBISCg5TRUNPTkRBUllfREFTSBAFKoABCghHYW1lTW9kZRIZChVHQU1FX01PREVfVU5TUEVDSUZJRUQQABIaChZHQU1FX01PREVfRlJFRV9GT1JfQUxMEAESHQoZR0FNRV9NT0RFX1RFQU1fREVBVEhNQVRDSBACEh4KGkdBTUVfTU9ERV9DQVBUVVJFX1RIRV9GTEFHEAMqigEKCUdhbWVTdGF0ZRIaChZHQU1FX1NUQVRFX1VOU1BFQ0lGSUVEEAASFgoSR0FNRV9TVEFURV9XQUlUSU5HEAESFwoTR0FNRV9TVEFURV9TVEFSVElORxACEhoKFkdBTUVfU1RBVEVfSU5fUFJPR1JFU1MQAxIUChBHQU1FX1NUQVRFX0VOREVEEAQqXAoFTWFwSWQSEwoPTUFQX1VOU1BFQ0lGSUVEEAASDQoJTUFQX0FSRU5BEAESDAoITUFQX01BWkUQAhIRCg1NQVBfV0FSRUhPVVNFEAMSDgoKTUFQX0NVU1RPTRAEYgZwcm90bzM");

/**
 * Enums - replace string keys for compact encoding
 *
 * @generated from enum gyrii.WeaponType
 */
export enum WeaponType {
  /**
   * @generated from enum value: WEAPON_UNSPECIFIED = 0;
   */
  WEAPON_UNSPECIFIED = 0,

  /**
   * @generated from enum value: WEAPON_SMG = 1;
   */
  WEAPON_SMG = 1,

  /**
   * @generated from enum value: WEAPON_DUAL_MACHINE_GUN = 2;
   */
  WEAPON_DUAL_MACHINE_GUN = 2,

  /**
   * @generated from enum value: WEAPON_CHAIN_GUN = 3;
   */
  WEAPON_CHAIN_GUN = 3,

  /**
   * @generated from enum value: WEAPON_PHOTON_RIFLE = 4;
   */
  WEAPON_PHOTON_RIFLE = 4,

  /**
   * @generated from enum value: WEAPON_BAZOOKA = 5;
   */
  WEAPON_BAZOOKA = 5,

  /**
   * @generated from enum value: WEAPON_FLAMETHROWER = 6;
   */
  WEAPON_FLAMETHROWER = 6,

  /**
   * @generated from enum value: WEAPON_SHOTGUN = 7;
   */
  WEAPON_SHOTGUN = 7,
}

/**
 * Describes the enum gyrii.WeaponType.
 */
export const WeaponTypeSchema: GenEnum<WeaponType> = /*@__PURE__*/
  enumDesc(file_common, 0);

/**
 * @generated from enum gyrii.SecondaryType
 */
export enum SecondaryType {
  /**
   * @generated from enum value: SECONDARY_UNSPECIFIED = 0;
   */
  SECONDARY_UNSPECIFIED = 0,

  /**
   * @generated from enum value: SECONDARY_POPUP_KNIVES = 1;
   */
  SECONDARY_POPUP_KNIVES = 1,

  /**
   * @generated from enum value: SECONDARY_BUBBLE_SHIELD = 2;
   */
  SECONDARY_BUBBLE_SHIELD = 2,

  /**
   * @generated from enum value: SECONDARY_SELF_DESTRUCT_NUKE = 3;
   */
  SECONDARY_SELF_DESTRUCT_NUKE = 3,

  /**
   * @generated from enum value: SECONDARY_POPUP_HAMMERS = 4;
   */
  SECONDARY_POPUP_HAMMERS = 4,

  /**
   * @generated from enum value: SECONDARY_DASH = 5;
   */
  SECONDARY_DASH = 5,
}

/**
 * Describes the enum gyrii.SecondaryType.
 */
export const SecondaryTypeSchema: GenEnum<SecondaryType> = /*@__PURE__*/
  enumDesc(file_common, 1);

/**
 * @generated from enum gyrii.GameMode
 */
export enum GameMode {
  /**
   * @generated from enum value: GAME_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GAME_MODE_FREE_FOR_ALL = 1;
   */
  FREE_FOR_ALL = 1,

  /**
   * @generated from enum value: GAME_MODE_TEAM_DEATHMATCH = 2;
   */
  TEAM_DEATHMATCH = 2,

  /**
   * @generated from enum value: GAME_MODE_CAPTURE_THE_FLAG = 3;
   */
  CAPTURE_THE_FLAG = 3,
}

/**
 * Describes the enum gyrii.GameMode.
 */
export const GameModeSchema: GenEnum<GameMode> = /*@__PURE__*/
  enumDesc(file_common, 2);

/**
 * @generated from enum gyrii.GameState
 */
export enum GameState {
  /**
   * @generated from enum value: GAME_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GAME_STATE_WAITING = 1;
   */
  WAITING = 1,

  /**
   * @generated from enum value: GAME_STATE_STARTING = 2;
   */
  STARTING = 2,

  /**
   * @generated from enum value: GAME_STATE_IN_PROGRESS = 3;
   */
  IN_PROGRESS = 3,

  /**
   * @generated from enum value: GAME_STATE_ENDED = 4;
   */
  ENDED = 4,
}

/**
 * Describes the enum gyrii.GameState.
 */
export const GameStateSchema: GenEnum<GameState> = /*@__PURE__*/
  enumDesc(file_common, 3);

/**
 * @generated from enum gyrii.MapId
 */
export enum MapId {
  /**
   * @generated from enum value: MAP_UNSPECIFIED = 0;
   */
  MAP_UNSPECIFIED = 0,

  /**
   * @generated from enum value: MAP_ARENA = 1;
   */
  MAP_ARENA = 1,

  /**
   * @generated from enum value: MAP_MAZE = 2;
   */
  MAP_MAZE = 2,

  /**
   * @generated from enum value: MAP_WAREHOUSE = 3;
   */
  MAP_WAREHOUSE = 3,

  /**
   * @generated from enum value: MAP_CUSTOM = 4;
   */
  MAP_CUSTOM = 4,
}

/**
 * Describes the enum gyrii.MapId.
 */
export const MapIdSchema: GenEnum<MapId> = /*@__PURE__*/
  enumDesc(file_common, 4);

