// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file delta.proto (package gyrii, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { PlayerRealtime } from "./player_pb";
import { file_player } from "./player_pb";
import type { GrenadeDelete, GrenadeInsert, GrenadeUpdate, KillEvent, PhotonBeam, SecondaryEffectEvent, ShotEvent } from "./combat_pb";
import { file_combat } from "./combat_pb";
import type { FlagState } from "./ctf_pb";
import { file_ctf } from "./ctf_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file delta.proto.
 */
export const file_delta: GenFile = /*@__PURE__*/
  fileDesc("CgtkZWx0YS5wcm90bxIFZ3lyaWkizAMKBURlbHRhEgwKBHRpY2sYASABKAQSEAoIZGVsdGFfaWQYAiABKAQSGAoQYmFzZV9zbmFwc2hvdF9pZBgDIAEoBBImCgdwbGF5ZXJzGAQgAygLMhUuZ3lyaWkuUGxheWVyUmVhbHRpbWUSJQoLc2hvdF9ldmVudHMYBSADKAsyEC5neXJpaS5TaG90RXZlbnQSLQoPZ3JlbmFkZV9pbnNlcnRzGAYgAygLMhQuZ3lyaWkuR3JlbmFkZUluc2VydBItCg9ncmVuYWRlX2RlbGV0ZXMYByADKAsyFC5neXJpaS5HcmVuYWRlRGVsZXRlEi0KD2dyZW5hZGVfdXBkYXRlcxgIIAMoCzIULmd5cmlpLkdyZW5hZGVVcGRhdGUSJQoLa2lsbF9ldmVudHMYCSADKAsyEC5neXJpaS5LaWxsRXZlbnQSJwoMcGhvdG9uX2JlYW1zGAogAygLMhEuZ3lyaWkuUGhvdG9uQmVhbRIfCgVmbGFncxgLIAMoCzIQLmd5cmlpLkZsYWdTdGF0ZRI8ChdzZWNvbmRhcnlfZWZmZWN0X2V2ZW50cxgMIAMoCzIbLmd5cmlpLlNlY29uZGFyeUVmZmVjdEV2ZW50YgZwcm90bzM", [file_player, file_combat, file_ctf]);

/**
 * Server -> Client: incremental update (each tick)
 *
 * @generated from message gyrii.Delta
 */
export type Delta = Message<"gyrii.Delta"> & {
  /**
   * @generated from field: uint64 tick = 1;
   */
  tick: bigint;

  /**
   * @generated from field: uint64 delta_id = 2;
   */
  deltaId: bigint;

  /**
   * @generated from field: uint64 base_snapshot_id = 3;
   */
  baseSnapshotId: bigint;

  /**
   * @generated from field: repeated gyrii.PlayerRealtime players = 4;
   */
  players: PlayerRealtime[];

  /**
   * @generated from field: repeated gyrii.ShotEvent shot_events = 5;
   */
  shotEvents: ShotEvent[];

  /**
   * @generated from field: repeated gyrii.GrenadeInsert grenade_inserts = 6;
   */
  grenadeInserts: GrenadeInsert[];

  /**
   * @generated from field: repeated gyrii.GrenadeDelete grenade_deletes = 7;
   */
  grenadeDeletes: GrenadeDelete[];

  /**
   * @generated from field: repeated gyrii.GrenadeUpdate grenade_updates = 8;
   */
  grenadeUpdates: GrenadeUpdate[];

  /**
   * @generated from field: repeated gyrii.KillEvent kill_events = 9;
   */
  killEvents: KillEvent[];

  /**
   * @generated from field: repeated gyrii.PhotonBeam photon_beams = 10;
   */
  photonBeams: PhotonBeam[];

  /**
   * @generated from field: repeated gyrii.FlagState flags = 11;
   */
  flags: FlagState[];

  /**
   * @generated from field: repeated gyrii.SecondaryEffectEvent secondary_effect_events = 12;
   */
  secondaryEffectEvents: SecondaryEffectEvent[];
};

/**
 * Describes the message gyrii.Delta.
 * Use `create(DeltaSchema)` to create a new message.
 */
export const DeltaSchema: GenMessage<Delta> = /*@__PURE__*/
  messageDesc(file_delta, 0);

