// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gyrii.proto (package gyrii, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_common } from "./common_pb";
import { file_player } from "./player_pb";
import type { GameEnded, LobbyList, LobbyState, PlayerJoined, PlayerLeft } from "./lobby_pb";
import { file_lobby } from "./lobby_pb";
import { file_combat } from "./combat_pb";
import type { Authenticate, CreateLobby, DetonateRocket, EndGame, JoinLobby, LeaveLobby, ListLobbies, RequestLobbyState, RequestSpawn, SetLoadout, SetMarbleConfig, SetReady, SetShooting, Shoot, StartGame, ThrowGrenade, ThrowMolotov, UpdateInput, UseSecondary } from "./actions_pb";
import { file_actions } from "./actions_pb";
import type { Delta } from "./delta_pb";
import { file_delta } from "./delta_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gyrii.proto.
 */
export const file_gyrii: GenFile = /*@__PURE__*/
  fileDesc("CgtneXJpaS5wcm90bxIFZ3lyaWkiGAoESW5pdBIQCghpZGVudGl0eRgBIAEoDCIQCgJPaxIKCgJvaxgBIAEoCCIWCgVFcnJvchINCgVlcnJvchgBIAEoCSLgAgoNU2VydmVyTWVzc2FnZRIbCgRpbml0GAEgASgLMgsuZ3lyaWkuSW5pdEgAEhcKAm9rGAIgASgLMgkuZ3lyaWkuT2tIABIdCgVlcnJvchgDIAEoCzIMLmd5cmlpLkVycm9ySAASKAoLbG9iYnlfc3RhdGUYBCABKAsyES5neXJpaS5Mb2JieVN0YXRlSAASJgoKbG9iYnlfbGlzdBgFIAEoCzIQLmd5cmlpLkxvYmJ5TGlzdEgAEh0KBWRlbHRhGAYgASgLMgwuZ3lyaWkuRGVsdGFIABIsCg1wbGF5ZXJfam9pbmVkGAcgASgLMhMuZ3lyaWkuUGxheWVySm9pbmVkSAASKAoLcGxheWVyX2xlZnQYCCABKAsyES5neXJpaS5QbGF5ZXJMZWZ0SAASJgoKZ2FtZV9lbmRlZBgJIAEoCzIQLmd5cmlpLkdhbWVFbmRlZEgAQgkKB21lc3NhZ2Ui3AYKDUNsaWVudE1lc3NhZ2USKwoMYXV0aGVudGljYXRlGAEgASgLMhMuZ3lyaWkuQXV0aGVudGljYXRlSAASKgoMbGlzdF9sb2JiaWVzGAIgASgLMhIuZ3lyaWkuTGlzdExvYmJpZXNIABIqCgxjcmVhdGVfbG9iYnkYAyABKAsyEi5neXJpaS5DcmVhdGVMb2JieUgAEiYKCmpvaW5fbG9iYnkYBCABKAsyEC5neXJpaS5Kb2luTG9iYnlIABI3ChNyZXF1ZXN0X2xvYmJ5X3N0YXRlGAUgASgLMhguZ3lyaWkuUmVxdWVzdExvYmJ5U3RhdGVIABIoCgtsZWF2ZV9sb2JieRgGIAEoCzIRLmd5cmlpLkxlYXZlTG9iYnlIABIkCglzZXRfcmVhZHkYByABKAsyDy5neXJpaS5TZXRSZWFkeUgAEiYKCnN0YXJ0X2dhbWUYCCABKAsyEC5neXJpaS5TdGFydEdhbWVIABIiCghlbmRfZ2FtZRgJIAEoCzIOLmd5cmlpLkVuZEdhbWVIABIsCg1yZXF1ZXN0X3NwYXduGAogASgLMhMuZ3lyaWkuUmVxdWVzdFNwYXduSAASKgoMdXBkYXRlX2lucHV0GAsgASgLMhIuZ3lyaWkuVXBkYXRlSW5wdXRIABIqCgxzZXRfc2hvb3RpbmcYDCABKAsyEi5neXJpaS5TZXRTaG9vdGluZ0gAEigKC3NldF9sb2Fkb3V0GA0gASgLMhEuZ3lyaWkuU2V0TG9hZG91dEgAEjMKEXNldF9tYXJibGVfY29uZmlnGA4gASgLMhYuZ3lyaWkuU2V0TWFyYmxlQ29uZmlnSAASHQoFc2hvb3QYDyABKAsyDC5neXJpaS5TaG9vdEgAEjAKD2RldG9uYXRlX3JvY2tldBgQIAEoCzIVLmd5cmlpLkRldG9uYXRlUm9ja2V0SAASLAoNdGhyb3dfZ3JlbmFkZRgRIAEoCzITLmd5cmlpLlRocm93R3JlbmFkZUgAEiwKDXRocm93X21vbG90b3YYEiABKAsyEy5neXJpaS5UaHJvd01vbG90b3ZIABIsCg11c2Vfc2Vjb25kYXJ5GBMgASgLMhMuZ3lyaWkuVXNlU2Vjb25kYXJ5SABCCQoHbWVzc2FnZWIGcHJvdG8z", [file_common, file_player, file_lobby, file_combat, file_actions, file_delta]);

/**
 * Server -> Client: init on connect
 *
 * @generated from message gyrii.Init
 */
export type Init = Message<"gyrii.Init"> & {
  /**
   * 16-byte UUID
   *
   * @generated from field: bytes identity = 1;
   */
  identity: Uint8Array;
};

/**
 * Describes the message gyrii.Init.
 * Use `create(InitSchema)` to create a new message.
 */
export const InitSchema: GenMessage<Init> = /*@__PURE__*/
  messageDesc(file_gyrii, 0);

/**
 * Server -> Client: success response
 *
 * @generated from message gyrii.Ok
 */
export type Ok = Message<"gyrii.Ok"> & {
  /**
   * @generated from field: bool ok = 1;
   */
  ok: boolean;
};

/**
 * Describes the message gyrii.Ok.
 * Use `create(OkSchema)` to create a new message.
 */
export const OkSchema: GenMessage<Ok> = /*@__PURE__*/
  messageDesc(file_gyrii, 1);

/**
 * Server -> Client: error response
 *
 * @generated from message gyrii.Error
 */
export type Error = Message<"gyrii.Error"> & {
  /**
   * @generated from field: string error = 1;
   */
  error: string;
};

/**
 * Describes the message gyrii.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema: GenMessage<Error> = /*@__PURE__*/
  messageDesc(file_gyrii, 2);

/**
 * Top-level wrapper: all server->client messages
 *
 * @generated from message gyrii.ServerMessage
 */
export type ServerMessage = Message<"gyrii.ServerMessage"> & {
  /**
   * @generated from oneof gyrii.ServerMessage.message
   */
  message: {
    /**
     * @generated from field: gyrii.Init init = 1;
     */
    value: Init;
    case: "init";
  } | {
    /**
     * @generated from field: gyrii.Ok ok = 2;
     */
    value: Ok;
    case: "ok";
  } | {
    /**
     * @generated from field: gyrii.Error error = 3;
     */
    value: Error;
    case: "error";
  } | {
    /**
     * @generated from field: gyrii.LobbyState lobby_state = 4;
     */
    value: LobbyState;
    case: "lobbyState";
  } | {
    /**
     * @generated from field: gyrii.LobbyList lobby_list = 5;
     */
    value: LobbyList;
    case: "lobbyList";
  } | {
    /**
     * @generated from field: gyrii.Delta delta = 6;
     */
    value: Delta;
    case: "delta";
  } | {
    /**
     * @generated from field: gyrii.PlayerJoined player_joined = 7;
     */
    value: PlayerJoined;
    case: "playerJoined";
  } | {
    /**
     * @generated from field: gyrii.PlayerLeft player_left = 8;
     */
    value: PlayerLeft;
    case: "playerLeft";
  } | {
    /**
     * @generated from field: gyrii.GameEnded game_ended = 9;
     */
    value: GameEnded;
    case: "gameEnded";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message gyrii.ServerMessage.
 * Use `create(ServerMessageSchema)` to create a new message.
 */
export const ServerMessageSchema: GenMessage<ServerMessage> = /*@__PURE__*/
  messageDesc(file_gyrii, 3);

/**
 * Client -> Server: all actions
 *
 * @generated from message gyrii.ClientMessage
 */
export type ClientMessage = Message<"gyrii.ClientMessage"> & {
  /**
   * @generated from oneof gyrii.ClientMessage.message
   */
  message: {
    /**
     * @generated from field: gyrii.Authenticate authenticate = 1;
     */
    value: Authenticate;
    case: "authenticate";
  } | {
    /**
     * @generated from field: gyrii.ListLobbies list_lobbies = 2;
     */
    value: ListLobbies;
    case: "listLobbies";
  } | {
    /**
     * @generated from field: gyrii.CreateLobby create_lobby = 3;
     */
    value: CreateLobby;
    case: "createLobby";
  } | {
    /**
     * @generated from field: gyrii.JoinLobby join_lobby = 4;
     */
    value: JoinLobby;
    case: "joinLobby";
  } | {
    /**
     * @generated from field: gyrii.RequestLobbyState request_lobby_state = 5;
     */
    value: RequestLobbyState;
    case: "requestLobbyState";
  } | {
    /**
     * @generated from field: gyrii.LeaveLobby leave_lobby = 6;
     */
    value: LeaveLobby;
    case: "leaveLobby";
  } | {
    /**
     * @generated from field: gyrii.SetReady set_ready = 7;
     */
    value: SetReady;
    case: "setReady";
  } | {
    /**
     * @generated from field: gyrii.StartGame start_game = 8;
     */
    value: StartGame;
    case: "startGame";
  } | {
    /**
     * @generated from field: gyrii.EndGame end_game = 9;
     */
    value: EndGame;
    case: "endGame";
  } | {
    /**
     * @generated from field: gyrii.RequestSpawn request_spawn = 10;
     */
    value: RequestSpawn;
    case: "requestSpawn";
  } | {
    /**
     * @generated from field: gyrii.UpdateInput update_input = 11;
     */
    value: UpdateInput;
    case: "updateInput";
  } | {
    /**
     * @generated from field: gyrii.SetShooting set_shooting = 12;
     */
    value: SetShooting;
    case: "setShooting";
  } | {
    /**
     * @generated from field: gyrii.SetLoadout set_loadout = 13;
     */
    value: SetLoadout;
    case: "setLoadout";
  } | {
    /**
     * @generated from field: gyrii.SetMarbleConfig set_marble_config = 14;
     */
    value: SetMarbleConfig;
    case: "setMarbleConfig";
  } | {
    /**
     * @generated from field: gyrii.Shoot shoot = 15;
     */
    value: Shoot;
    case: "shoot";
  } | {
    /**
     * @generated from field: gyrii.DetonateRocket detonate_rocket = 16;
     */
    value: DetonateRocket;
    case: "detonateRocket";
  } | {
    /**
     * @generated from field: gyrii.ThrowGrenade throw_grenade = 17;
     */
    value: ThrowGrenade;
    case: "throwGrenade";
  } | {
    /**
     * @generated from field: gyrii.ThrowMolotov throw_molotov = 18;
     */
    value: ThrowMolotov;
    case: "throwMolotov";
  } | {
    /**
     * @generated from field: gyrii.UseSecondary use_secondary = 19;
     */
    value: UseSecondary;
    case: "useSecondary";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message gyrii.ClientMessage.
 * Use `create(ClientMessageSchema)` to create a new message.
 */
export const ClientMessageSchema: GenMessage<ClientMessage> = /*@__PURE__*/
  messageDesc(file_gyrii, 4);

