// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file lobby.proto (package gyrii, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { GameMode, GameState, MapId } from "./common_pb";
import { file_common } from "./common_pb";
import type { Player, PlayerProfile } from "./player_pb";
import { file_player } from "./player_pb";
import type { FlagState } from "./ctf_pb";
import { file_ctf } from "./ctf_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file lobby.proto.
 */
export const file_lobby: GenFile = /*@__PURE__*/
  fileDesc("Cgtsb2JieS5wcm90bxIFZ3lyaWkiiQMKBUxvYmJ5EgoKAmlkGAEgASgEEgwKBG5hbWUYAiABKAkSDwoHaG9zdF9pZBgDIAEoDBIcCgZtYXBfaWQYBCABKA4yDC5neXJpaS5NYXBJZBIeCghtYXBfcG9vbBgFIAMoDjIMLmd5cmlpLk1hcElkEhMKC21heF9wbGF5ZXJzGAYgASgNEiIKCWdhbWVfbW9kZRgHIAEoDjIPLmd5cmlpLkdhbWVNb2RlEiQKCmdhbWVfc3RhdGUYCCABKA4yEC5neXJpaS5HYW1lU3RhdGUSEwoLc2NvcmVfbGltaXQYCSABKAUSEgoKZmxhZ19saW1pdBgKIAEoBRIkChduZXh0X3JvdW5kX3N0YXJ0c19hdF9tcxgLIAEoBEgAiAEBEhUKDWlzX2N1c3RvbV9tYXAYDCABKAgSFQoIbWFwX2pzb24YDSABKAlIAYgBARISCgp0ZWFtX2NvdW50GA4gASgFQhoKGF9uZXh0X3JvdW5kX3N0YXJ0c19hdF9tc0ILCglfbWFwX2pzb24ilgEKCkxvYmJ5U3RhdGUSEwoLc25hcHNob3RfaWQYASABKAQSFQoNbGFzdF9kZWx0YV9pZBgCIAEoBBIbCgVsb2JieRgDIAEoCzIMLmd5cmlpLkxvYmJ5Eh4KB3BsYXllcnMYBCADKAsyDS5neXJpaS5QbGF5ZXISHwoFZmxhZ3MYBSADKAsyEC5neXJpaS5GbGFnU3RhdGUimAMKDExvYmJ5U3VtbWFyeRIKCgJpZBgBIAEoBBIMCgRuYW1lGAIgASgJEg8KB2hvc3RfaWQYAyABKAwSHAoGbWFwX2lkGAQgASgOMgwuZ3lyaWkuTWFwSWQSHgoIbWFwX3Bvb2wYBSADKA4yDC5neXJpaS5NYXBJZBITCgttYXhfcGxheWVycxgGIAEoDRIUCgxwbGF5ZXJfY291bnQYByABKA0SIgoJZ2FtZV9tb2RlGAggASgOMg8uZ3lyaWkuR2FtZU1vZGUSJAoKZ2FtZV9zdGF0ZRgJIAEoDjIQLmd5cmlpLkdhbWVTdGF0ZRIUCgxoYXNfcGFzc3dvcmQYCiABKAgSEwoLc2NvcmVfbGltaXQYCyABKAUSEgoKZmxhZ19saW1pdBgMIAEoBRIkChduZXh0X3JvdW5kX3N0YXJ0c19hdF9tcxgNIAEoBEgAiAEBEhUKDWlzX2N1c3RvbV9tYXAYDiABKAgSEgoKdGVhbV9jb3VudBgPIAEoBUIaChhfbmV4dF9yb3VuZF9zdGFydHNfYXRfbXMiMQoJTG9iYnlMaXN0EiQKB2xvYmJpZXMYASADKAsyEy5neXJpaS5Mb2JieVN1bW1hcnkiNAoMUGxheWVySm9pbmVkEiQKBnBsYXllchgBIAEoCzIULmd5cmlpLlBsYXllclByb2ZpbGUiHwoKUGxheWVyTGVmdBIRCglwbGF5ZXJfaWQYASABKAwi+AEKCUdhbWVFbmRlZBIQCghsb2JieV9pZBgBIAEoBBIYCgt3aW5uZXJfdGVhbRgCIAEoBUgAiAEBEiMKFndpbm5lcl9wbGF5ZXJfaWRlbnRpdHkYAyABKAxIAYgBARIfChJ3aW5uZXJfcGxheWVyX25hbWUYBCABKAlIAogBARIhCgtuZXh0X21hcF9pZBgFIAEoDjIMLmd5cmlpLk1hcElkEhQKDGNvdW50ZG93bl9tcxgGIAEoBEIOCgxfd2lubmVyX3RlYW1CGQoXX3dpbm5lcl9wbGF5ZXJfaWRlbnRpdHlCFQoTX3dpbm5lcl9wbGF5ZXJfbmFtZWIGcHJvdG8z", [file_common, file_player, file_ctf]);

/**
 * Lobby payload (full)
 *
 * @generated from message gyrii.Lobby
 */
export type Lobby = Message<"gyrii.Lobby"> & {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * 16-byte UUID
   *
   * @generated from field: bytes host_id = 3;
   */
  hostId: Uint8Array;

  /**
   * @generated from field: gyrii.MapId map_id = 4;
   */
  mapId: MapId;

  /**
   * @generated from field: repeated gyrii.MapId map_pool = 5;
   */
  mapPool: MapId[];

  /**
   * @generated from field: uint32 max_players = 6;
   */
  maxPlayers: number;

  /**
   * @generated from field: gyrii.GameMode game_mode = 7;
   */
  gameMode: GameMode;

  /**
   * @generated from field: gyrii.GameState game_state = 8;
   */
  gameState: GameState;

  /**
   * @generated from field: int32 score_limit = 9;
   */
  scoreLimit: number;

  /**
   * @generated from field: int32 flag_limit = 10;
   */
  flagLimit: number;

  /**
   * @generated from field: optional uint64 next_round_starts_at_ms = 11;
   */
  nextRoundStartsAtMs?: bigint;

  /**
   * @generated from field: bool is_custom_map = 12;
   */
  isCustomMap: boolean;

  /**
   * @generated from field: optional string map_json = 13;
   */
  mapJson?: string;

  /**
   * 2-4 for team modes; default 2
   *
   * @generated from field: int32 team_count = 14;
   */
  teamCount: number;
};

/**
 * Describes the message gyrii.Lobby.
 * Use `create(LobbySchema)` to create a new message.
 */
export const LobbySchema: GenMessage<Lobby> = /*@__PURE__*/
  messageDesc(file_lobby, 0);

/**
 * Server -> Client: full lobby state (on join)
 *
 * @generated from message gyrii.LobbyState
 */
export type LobbyState = Message<"gyrii.LobbyState"> & {
  /**
   * @generated from field: uint64 snapshot_id = 1;
   */
  snapshotId: bigint;

  /**
   * @generated from field: uint64 last_delta_id = 2;
   */
  lastDeltaId: bigint;

  /**
   * @generated from field: gyrii.Lobby lobby = 3;
   */
  lobby?: Lobby;

  /**
   * @generated from field: repeated gyrii.Player players = 4;
   */
  players: Player[];

  /**
   * @generated from field: repeated gyrii.FlagState flags = 5;
   */
  flags: FlagState[];
};

/**
 * Describes the message gyrii.LobbyState.
 * Use `create(LobbyStateSchema)` to create a new message.
 */
export const LobbyStateSchema: GenMessage<LobbyState> = /*@__PURE__*/
  messageDesc(file_lobby, 1);

/**
 * Lobby summary for list
 *
 * @generated from message gyrii.LobbySummary
 */
export type LobbySummary = Message<"gyrii.LobbySummary"> & {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: bytes host_id = 3;
   */
  hostId: Uint8Array;

  /**
   * @generated from field: gyrii.MapId map_id = 4;
   */
  mapId: MapId;

  /**
   * @generated from field: repeated gyrii.MapId map_pool = 5;
   */
  mapPool: MapId[];

  /**
   * @generated from field: uint32 max_players = 6;
   */
  maxPlayers: number;

  /**
   * @generated from field: uint32 player_count = 7;
   */
  playerCount: number;

  /**
   * @generated from field: gyrii.GameMode game_mode = 8;
   */
  gameMode: GameMode;

  /**
   * @generated from field: gyrii.GameState game_state = 9;
   */
  gameState: GameState;

  /**
   * @generated from field: bool has_password = 10;
   */
  hasPassword: boolean;

  /**
   * @generated from field: int32 score_limit = 11;
   */
  scoreLimit: number;

  /**
   * @generated from field: int32 flag_limit = 12;
   */
  flagLimit: number;

  /**
   * @generated from field: optional uint64 next_round_starts_at_ms = 13;
   */
  nextRoundStartsAtMs?: bigint;

  /**
   * @generated from field: bool is_custom_map = 14;
   */
  isCustomMap: boolean;

  /**
   * 2-4 for team modes; default 2
   *
   * @generated from field: int32 team_count = 15;
   */
  teamCount: number;
};

/**
 * Describes the message gyrii.LobbySummary.
 * Use `create(LobbySummarySchema)` to create a new message.
 */
export const LobbySummarySchema: GenMessage<LobbySummary> = /*@__PURE__*/
  messageDesc(file_lobby, 2);

/**
 * Server -> Client: list of available lobbies
 *
 * @generated from message gyrii.LobbyList
 */
export type LobbyList = Message<"gyrii.LobbyList"> & {
  /**
   * @generated from field: repeated gyrii.LobbySummary lobbies = 1;
   */
  lobbies: LobbySummary[];
};

/**
 * Describes the message gyrii.LobbyList.
 * Use `create(LobbyListSchema)` to create a new message.
 */
export const LobbyListSchema: GenMessage<LobbyList> = /*@__PURE__*/
  messageDesc(file_lobby, 3);

/**
 * Sent when a new player spawns (broadcast to lobby)
 *
 * @generated from message gyrii.PlayerJoined
 */
export type PlayerJoined = Message<"gyrii.PlayerJoined"> & {
  /**
   * @generated from field: gyrii.PlayerProfile player = 1;
   */
  player?: PlayerProfile;
};

/**
 * Describes the message gyrii.PlayerJoined.
 * Use `create(PlayerJoinedSchema)` to create a new message.
 */
export const PlayerJoinedSchema: GenMessage<PlayerJoined> = /*@__PURE__*/
  messageDesc(file_lobby, 4);

/**
 * Sent when a player leaves a lobby (broadcast to lobby)
 *
 * @generated from message gyrii.PlayerLeft
 */
export type PlayerLeft = Message<"gyrii.PlayerLeft"> & {
  /**
   * 16-byte UUID
   *
   * @generated from field: bytes player_id = 1;
   */
  playerId: Uint8Array;
};

/**
 * Describes the message gyrii.PlayerLeft.
 * Use `create(PlayerLeftSchema)` to create a new message.
 */
export const PlayerLeftSchema: GenMessage<PlayerLeft> = /*@__PURE__*/
  messageDesc(file_lobby, 5);

/**
 * Game ended
 *
 * @generated from message gyrii.GameEnded
 */
export type GameEnded = Message<"gyrii.GameEnded"> & {
  /**
   * @generated from field: uint64 lobby_id = 1;
   */
  lobbyId: bigint;

  /**
   * @generated from field: optional int32 winner_team = 2;
   */
  winnerTeam?: number;

  /**
   * @generated from field: optional bytes winner_player_identity = 3;
   */
  winnerPlayerIdentity?: Uint8Array;

  /**
   * @generated from field: optional string winner_player_name = 4;
   */
  winnerPlayerName?: string;

  /**
   * @generated from field: gyrii.MapId next_map_id = 5;
   */
  nextMapId: MapId;

  /**
   * @generated from field: uint64 countdown_ms = 6;
   */
  countdownMs: bigint;
};

/**
 * Describes the message gyrii.GameEnded.
 * Use `create(GameEndedSchema)` to create a new message.
 */
export const GameEndedSchema: GenMessage<GameEnded> = /*@__PURE__*/
  messageDesc(file_lobby, 6);

